export const countries = [
    {
        name: 'Germany',
        viewMoreLink: '/study-abroad/germany',
        courses: [
            {
                id: 'germany-engineering',
                name: 'Engineering',
                img: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&h=300&fit=crop',
                alt: 'Engineering in Germany',
                description: 'World-class engineering programs in mechanical, automotive, and electrical engineering with strong industry partnerships and research opportunities.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: '€0 - €20,000/year (Public universities often free)',
                entryRequirements: 'Relevant Bachelor’s, German B2/C1 or English IELTS 6.5+',
                careerProspects: 'Engineer, R&D Specialist, Automotive Expert',
                universities: ['Technical University of Munich', 'RWTH Aachen University', 'Karlsruhe Institute of Technology'],
                link: '/course/germany/engineering',
            },
            {
                id: 'germany-computer-science',
                name: 'Computer Science',
                img: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=500&h=300&fit=crop',
                alt: 'Computer Science in Germany',
                description: 'Cutting-edge programs in AI, software development, and data science with collaborations from tech giants like SAP and Siemens.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: '€0 - €15,000/year',
                entryRequirements: 'CS Bachelor’s, GRE optional, Programming skills',
                careerProspects: 'Software Developer, Data Scientist, IT Consultant',
                universities: ['Technical University of Munich', 'University of Freiburg', 'Ludwig Maximilian University'],
                link: '/course/germany/computer-science',
            },
            {
                id: 'germany-business-administration',
                name: 'Business Administration',
                img: 'https://images.unsplash.com/photo-1552664730-d307c8eaa005?w=500&h=300&fit=crop',
                alt: 'Business in Germany',
                description: 'International business, management, and economics education in Europe\'s economic powerhouse with global networking opportunities.',
                duration: '18-24 Months',
                qualification: 'MBA/Masters',
                tuition: '€10,000 - €30,000/year',
                entryRequirements: 'Bachelor’s, GMAT, Work experience',
                careerProspects: 'Manager, Consultant, Entrepreneur',
                universities: ['Mannheim Business School', 'WHU Otto Beisheim', 'Frankfurt School of Finance'],
                link: '/course/germany/business-administration',
            },
            {
                id: 'germany-automotive-engineering',
                name: 'Automotive Engineering',
                img: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=500&h=300&fit=crop',
                alt: 'Automotive in Germany',
                description: 'Specialized programs in electric vehicles, autonomous driving, and automotive design with direct industry connections to BMW and Volkswagen.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: '€0 - €18,000/year',
                entryRequirements: 'Mechanical Engineering degree, IELTS 6.5+',
                careerProspects: 'Automotive Engineer, Designer, Researcher',
                universities: ['RWTH Aachen', 'Technical University of Munich', 'University of Stuttgart'],
                link: '/course/germany/automotive-engineering',
            },
            {
                id: 'germany-data-science-ai',
                name: 'Data Science & AI',
                img: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=500&h=300&fit=crop',
                alt: 'Data Science in Germany',
                description: 'Advanced machine learning, big data analytics, and AI ethics programs with access to cutting-edge research facilities.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: '€0 - €15,000/year',
                entryRequirements: 'STEM degree, Programming knowledge',
                careerProspects: 'Data Scientist, AI Engineer',
                universities: ['University of Tübingen', 'Technical University of Berlin', 'Max Planck Institutes'],
                link: '/course/germany/data-science-ai',
            },
            {
                id: 'germany-renewable-energy',
                name: 'Renewable Energy',
                img: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=500&h=300&fit=crop',
                alt: 'Renewable Energy in Germany',
                description: 'Sustainable energy systems, wind and solar technology, and environmental engineering in a global renewable energy leader.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: '€0 - €12,000/year',
                entryRequirements: 'Engineering/Science degree, IELTS 6.0+',
                careerProspects: 'Energy Consultant, Researcher, Engineer',
                universities: ['University of Oldenburg', 'Technical University of Berlin', 'Freiburg University'],
                link: '/course/germany/renewable-energy',
            },
            {
                id: 'germany-medicine',
                name: 'Medicine',
                img: 'https://images.unsplash.com/photo-1551076805-e1869033e561?w=500&h=300&fit=crop',
                alt: 'Medicine in Germany',
                description: 'Comprehensive medical education with extensive clinical training and research opportunities in world-renowned hospitals.',
                duration: '72 Months',
                qualification: 'State Examination',
                tuition: '€0 - €10,000/semester fees',
                entryRequirements: 'Abitur equivalent, German C1, TestAS',
                careerProspects: 'Doctor, Specialist, Researcher',
                universities: ['Heidelberg University', 'Charité Berlin', 'LMU Munich'],
                link: '/course/germany/medicine',
            },
            {
                id: 'germany-economics',
                name: 'Economics',
                img: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=500&h=300&fit=crop',
                alt: 'Economics in Germany',
                description: 'Macroeconomics, finance, and policy analysis in Europe\'s largest economy with strong industry and government connections.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: '€0 - €20,000/year',
                entryRequirements: 'Economics Bachelor’s, GRE optional',
                careerProspects: 'Economist, Analyst, Policy Advisor',
                universities: ['University of Mannheim', 'LMU Munich', 'Humboldt University Berlin'],
                link: '/course/germany/economics',
            },
        ],
    },
    {
        name: 'UK',
        viewMoreLink: '/study-abroad/uk',
        courses: [
            {
                id: 'uk-business-management',
                name: 'Business Management',
                img: 'https://images.unsplash.com/photo-1552664730-d307c8eaa005?w=500&h=300&fit=crop',
                alt: 'Business management courses in UK',
                description: 'Master international business strategies, leadership, and global market dynamics with top UK universities like Oxford and Cambridge.',
                duration: '12-24 Months',
                qualification: 'Masters Degree',
                tuition: '£15,000 - £30,000/year',
                entryRequirements: 'Bachelor’s degree with 60%+, IELTS 6.5+',
                careerProspects: 'Business Analyst, Manager, Entrepreneur',
                universities: ['University of Oxford', 'London Business School', 'Imperial College London'],
                link: '/course/uk/business-management',
            },
            {
                id: 'uk-engineering',
                name: 'Engineering',
                img: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&h=300&fit=crop',
                alt: 'Engineering courses in UK',
                description: 'Innovative programs in mechanical, civil, and electrical engineering with focus on sustainability and cutting-edge technology.',
                duration: '12-36 Months',
                qualification: 'Bachelors/Masters',
                tuition: '£18,000 - £35,000/year',
                entryRequirements: 'Relevant Bachelor’s, IELTS 6.0+',
                careerProspects: 'Engineer, Project Manager, Researcher',
                universities: ['University of Cambridge', 'Imperial College London', 'University of Manchester'],
                link: '/course/uk/engineering',
            },
            {
                id: 'uk-computer-science',
                name: 'Computer Science',
                img: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=500&h=300&fit=crop',
                alt: 'Computer science in UK',
                description: 'Comprehensive studies in AI, cybersecurity, software development, and data analytics with industry partnerships.',
                duration: '12-24 Months',
                qualification: 'Masters Degree',
                tuition: '£20,000 - £40,000/year',
                entryRequirements: 'Computer-related degree, IELTS 6.5+',
                careerProspects: 'Software Developer, Data Scientist, IT Consultant',
                universities: ['University of Edinburgh', 'University College London', 'King’s College London'],
                link: '/course/uk/computer-science',
            },
            {
                id: 'uk-law',
                name: 'Law',
                img: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=500&h=300&fit=crop',
                alt: 'law-uk',
                description: 'Prestigious LLB and LLM programs in international law, human rights, and corporate law with global recognition.',
                duration: '36 Months',
                qualification: 'Bachelors/LLM',
                tuition: '£15,000 - £25,000/year',
                entryRequirements: 'Bachelor’s in any field, IELTS 7.0+',
                careerProspects: 'Lawyer, Solicitor, Legal Advisor',
                universities: ['University of Oxford', 'University of Cambridge', 'London School of Economics'],
                link: '/course/uk/law',
            },
            {
                id: 'uk-finance',
                name: 'Finance',
                img: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=500&h=300&fit=crop',
                alt: 'Finance courses in UK',
                description: 'Advanced financial markets, investment banking, and risk management programs with CFA-aligned curricula.',
                duration: '12 Months',
                qualification: 'Masters',
                tuition: '£25,000 - £45,000/year',
                entryRequirements: 'Finance-related degree, GMAT optional',
                careerProspects: 'Financial Analyst, Investment Banker, Accountant',
                universities: ['London School of Economics', 'University of Warwick', 'City University London'],
                link: '/course/uk/finance',
            },
            {
                id: 'uk-architecture',
                name: 'Architecture',
                img: 'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=500&h=300&fit=crop',
                alt: 'Architecture in UK',
                description: 'Sustainable building design and urban planning with focus on innovation and environmental impact.',
                duration: '24-36 Months',
                qualification: 'Masters',
                tuition: '£18,000 - £30,000/year',
                entryRequirements: 'Architecture Bachelor’s, Portfolio required',
                careerProspects: 'Architect, Urban Planner, Designer',
                universities: ['Architectural Association School', 'University of Sheffield', 'Bartlett School of Architecture'],
                link: '/course/uk/architecture',
            },
            {
                id: 'uk-data-science',
                name: 'Data Science & AI',
                img: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=500&h=300&fit=crop',
                alt: 'Data Science in UK',
                description: 'Big data analytics, AI model development, and machine learning applications in real-world scenarios.',
                duration: '12 Months',
                qualification: 'Masters',
                tuition: '£22,000 - £38,000/year',
                entryRequirements: 'STEM degree, Programming knowledge',
                careerProspects: 'Data Scientist, AI Engineer, Analyst',
                universities: ['University of Manchester', 'University of Bristol', 'Imperial College London'],
                link: '/course/uk/data-science-ai',
            },
            {
                id: 'uk-cybersecurity',
                name: 'Cybersecurity',
                img: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=500&h=300&fit=crop',
                alt: 'Cybersecurity in UK',
                description: 'Digital asset protection, ethical hacking, and advanced security protocols in a digitally advanced economy.',
                duration: '12-24 Months',
                qualification: 'Masters',
                tuition: '£20,000 - £35,000/year',
                entryRequirements: 'IT degree, IELTS 6.5+',
                careerProspects: 'Cybersecurity Analyst, Ethical Hacker, Security Consultant',
                universities: ['Royal Holloway University', 'University of Southampton', 'Lancaster University'],
                link: '/course/uk/cybersecurity',
            },
            {
                id: 'uk-medicine',
                name: 'Medicine',
                img: 'https://images.unsplash.com/photo-1551076805-e1869033e561?w=500&h=300&fit=crop',
                alt: 'Medicine in UK',
                description: 'World-class medical training with extensive clinical placements and cutting-edge research opportunities.',
                duration: '60 Months',
                qualification: 'MBBS',
                tuition: '£30,000 - £50,000/year',
                entryRequirements: 'A-Levels in Sciences, UKCAT/BMAT',
                careerProspects: 'Doctor, Surgeon, Researcher',
                universities: ['University of Oxford', 'University of Cambridge', 'Imperial College London'],
                link: '/course/uk/medicine',
            },
        ],
    },
    {
        name: 'USA',
        viewMoreLink: '/study-abroad/usa',
        courses: [
            {
                id: 'usa-it-computer-science',
                name: 'IT & Computer Science',
                img: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=500&h=300&fit=crop',
                alt: 'IT in USA',
                description: 'Silicon Valley-inspired programs in software engineering, networks, and cloud computing with industry connections.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: '$30,000 - $60,000/year',
                entryRequirements: 'Bachelor’s in CS, GRE optional',
                careerProspects: 'Software Engineer, Network Admin, Tech Consultant',
                universities: ['Stanford University', 'MIT', 'Carnegie Mellon University'],
                link: '/course/usa/it-computer-science',
            },
            {
                id: 'usa-engineering',
                name: 'Engineering',
                img: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&h=300&fit=crop',
                alt: 'Engineering in USA',
                description: 'Innovative STEM programs in aerospace, bioengineering, and robotics with hands-on research opportunities.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: '$35,000 - $70,000/year',
                entryRequirements: 'Engineering Bachelor’s, GRE',
                careerProspects: 'Engineer, R&D Specialist, Project Lead',
                universities: ['MIT', 'California Institute of Technology', 'University of California Berkeley'],
                link: '/course/usa/engineering',
            },
            {
                id: 'usa-business-administration',
                name: 'Business Administration',
                img: 'https://images.unsplash.com/photo-1552664730-d307c8eaa005?w=500&h=300&fit=crop',
                alt: 'MBA in USA',
                description: 'Elite B-school programs focusing on entrepreneurship, global business strategy, and leadership development.',
                duration: '24 Months',
                qualification: 'MBA',
                tuition: '$50,000 - $100,000/year',
                entryRequirements: 'Bachelor’s, GMAT/GRE, Work experience',
                careerProspects: 'CEO, Consultant, Manager',
                universities: ['Harvard Business School', 'Stanford GSB', 'Wharton School'],
                link: '/course/usa/business-administration',
            },
            {
                id: 'usa-finance',
                name: 'Finance',
                img: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=500&h=300&fit=crop',
                alt: 'Finance in USA',
                description: 'Wall Street-focused courses in corporate finance, fintech innovation, and investment strategies.',
                duration: '12 Months',
                qualification: 'Masters',
                tuition: '$40,000 - $80,000/year',
                entryRequirements: 'Finance degree, GMAT',
                careerProspects: 'Investment Banker, Financial Advisor, Trader',
                universities: ['New York University', 'University of Chicago Booth', 'Columbia Business School'],
                link: '/course/usa/finance',
            },
            {
                id: 'usa-data-science',
                name: 'Data Science',
                img: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=500&h=300&fit=crop',
                alt: 'Data Science in USA',
                description: 'Big data analytics, machine learning applications, and predictive modeling in tech-driven environments.',
                duration: '18 Months',
                qualification: 'Masters',
                tuition: '$45,000 - $75,000/year',
                entryRequirements: 'STEM background, Programming skills',
                careerProspects: 'Data Analyst, Machine Learning Engineer',
                universities: ['University of California Berkeley', 'Carnegie Mellon', 'New York University'],
                link: '/course/usa/data-science',
            },
            {
                id: 'usa-biotechnology',
                name: 'Biotechnology',
                img: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=500&h=300&fit=crop',
                alt: 'Biotech in USA',
                description: 'Biomedical research, genetic engineering, and pharmaceutical development in world-leading research institutions.',
                duration: '24 Months',
                qualification: 'PhD/Masters',
                tuition: '$40,000 - $60,000/year',
                entryRequirements: 'Biology degree, GRE',
                careerProspects: 'Biotech Researcher, Lab Scientist',
                universities: ['Harvard University', 'MIT', 'University of California San Francisco'],
                link: '/course/usa/biotechnology',
            },
            {
                id: 'usa-medicine',
                name: 'Medicine',
                img: 'https://images.unsplash.com/photo-1551076805-e1869033e561?w=500&h=300&fit=crop',
                alt: 'Medicine in USA',
                description: 'Advanced healthcare training with clinical residencies and medical specializations in top hospitals.',
                duration: '48 Months',
                qualification: 'MD',
                tuition: '$50,000 - $80,000/year',
                entryRequirements: 'Bachelor’s, MCAT',
                careerProspects: 'Physician, Surgeon, Specialist',
                universities: ['Johns Hopkins University', 'Harvard Medical School', 'Mayo Clinic School'],
                link: '/course/usa/medicine',
            },
            {
                id: 'usa-ai-machine-learning',
                name: 'AI & Machine Learning',
                img: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=500&h=300&fit=crop',
                alt: 'AI in USA',
                description: 'Pioneering AI technologies, deep learning systems, and neural network development in innovation hubs.',
                duration: '12 Months',
                qualification: 'Masters',
                tuition: '$55,000 - $90,000/year',
                entryRequirements: 'CS degree, Python knowledge',
                careerProspects: 'AI Researcher, ML Engineer',
                universities: ['Stanford University', 'Carnegie Mellon', 'MIT'],
                link: '/course/usa/ai-machine-learning',
            },
        ],
    },
    {
        name: 'Canada',
        viewMoreLink: '/study-abroad/canada',
        courses: [
            {
                id: 'canada-business-administration',
                name: 'Business Administration',
                img: 'https://images.unsplash.com/photo-1552664730-d307c8eaa005?w=500&h=300&fit=crop',
                alt: 'Business in Canada',
                description: 'Sustainable business practices and international trade education in a diverse economic landscape.',
                duration: '24 Months',
                qualification: 'MBA',
                tuition: 'CAD 20,000 - 50,000/year',
                entryRequirements: 'Bachelor’s, GMAT, Work experience',
                careerProspects: 'Business Manager, Entrepreneur, Consultant',
                universities: ['University of Toronto Rotman', 'University of British Columbia Sauder', 'McGill University Desautels'],
                link: '/course/canada/business-administration',
            },
            {
                id: 'canada-engineering',
                name: 'Engineering',
                img: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&h=300&fit=crop',
                alt: 'Engineering in Canada',
                description: 'Specialized programs in mining, environmental, and software engineering with co-op opportunities.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: 'CAD 25,000 - 45,000/year',
                entryRequirements: 'Engineering degree, IELTS 6.5+',
                careerProspects: 'Engineer, Project Manager',
                universities: ['University of Toronto', 'University of Waterloo', 'University of British Columbia'],
                link: '/course/canada/engineering',
            },
            {
                id: 'canada-computer-science',
                name: 'Computer Science',
                img: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=500&h=300&fit=crop',
                alt: 'Computer Science in Canada',
                description: 'AI research, cybersecurity, and big data analytics with strong industry partnerships and co-op programs.',
                duration: '12-24 Months',
                qualification: 'Masters',
                tuition: 'CAD 20,000 - 40,000/year',
                entryRequirements: 'CS degree, GRE optional',
                careerProspects: 'Developer, Analyst, Tech Specialist',
                universities: ['University of Toronto', 'University of Waterloo', 'University of Montreal'],
                link: '/course/canada/computer-science',
            },
            {
                id: 'canada-hospitality-tourism',
                name: 'Hospitality & Tourism',
                img: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&h=300&fit=crop',
                alt: 'Hospitality in Canada',
                description: 'Hotel management, event planning, and sustainable tourism in a country renowned for its natural beauty.',
                duration: '24 Months',
                qualification: 'Diploma/Masters',
                tuition: 'CAD 15,000 - 30,000/year',
                entryRequirements: 'High School, IELTS 6.0+',
                careerProspects: 'Hotel Manager, Tour Operator',
                universities: ['George Brown College', 'Vancouver Island University', 'Ryerson University'],
                link: '/course/canada/hospitality-tourism',
            },
            {
                id: 'canada-education',
                name: 'Education',
                img: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=500&h=300&fit=crop',
                alt: 'Education in Canada',
                description: 'Teacher training, educational leadership, and innovative pedagogy in a multicultural environment.',
                duration: '12 Months',
                qualification: 'Masters',
                tuition: 'CAD 18,000 - 35,000/year',
                entryRequirements: 'Bachelor’s in Education, Teaching experience',
                careerProspects: 'Teacher, Administrator, Curriculum Developer',
                universities: ['University of British Columbia', 'University of Toronto OISE', 'University of Alberta'],
                link: '/course/canada/education',
            },
            {
                id: 'canada-environmental-science',
                name: 'Environmental Science',
                img: 'https://images.unsplash.com/photo-1418065460487-3e41a6c84dc5?w=500&h=300&fit=crop',
                alt: 'Environmental Science in Canada',
                description: 'Climate change research, conservation biology, and resource management in diverse ecosystems.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: 'CAD 20,000 - 40,000/year',
                entryRequirements: 'Science degree, IELTS 6.5+',
                careerProspects: 'Environmental Consultant, Researcher',
                universities: ['University of Waterloo', 'Dalhousie University', 'University of Guelph'],
                link: '/course/canada/environmental-science',
            },
            {
                id: 'canada-data-science-ai',
                name: 'Data Science & AI',
                img: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=500&h=300&fit=crop',
                alt: 'Data Science in Canada',
                description: 'Machine learning applications, data visualization, and predictive analytics in growing tech hubs.',
                duration: '12 Months',
                qualification: 'Masters',
                tuition: 'CAD 25,000 - 45,000/year',
                entryRequirements: 'STEM degree, Programming',
                careerProspects: 'Data Scientist, AI Specialist',
                universities: ['University of Toronto', 'University of British Columbia', 'McGill University'],
                link: '/course/canada/data-science-ai',
            },
            {
                id: 'canada-law',
                name: 'Law',
                img: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=500&h=300&fit=crop',
                alt: 'Law in Canada',
                description: 'JD programs with comprehensive focus on Canadian law, international regulations, and legal practice.',
                duration: '36 Months',
                qualification: 'JD',
                tuition: 'CAD 30,000 - 50,000/year',
                entryRequirements: 'Bachelor’s, LSAT',
                careerProspects: 'Lawyer, Judge, Legal Consultant',
                universities: ['University of Toronto', 'McGill University', 'University of British Columbia'],
                link: '/course/canada/law',
            },
            {
                id: 'canada-nursing',
                name: 'Nursing',
                img: 'https://images.unsplash.com/photo-1584614375600-7f7a3b9d0ee5?w=500&h=300&fit=crop',
                alt: 'Nursing in Canada',
                description: 'Clinical practice excellence, public health initiatives, and nursing leadership in advanced healthcare systems.',
                duration: '48 Months',
                qualification: 'BScN',
                tuition: 'CAD 20,000 - 40,000/year',
                entryRequirements: 'High School Sciences, IELTS 7.0+',
                careerProspects: 'Registered Nurse, Nurse Practitioner',
                universities: ['University of Alberta', 'University of Toronto', 'McMaster University'],
                link: '/course/canada/nursing',
            },
        ],
    },
    {
        name: 'Australia',
        viewMoreLink: '/study-abroad/australia',
        courses: [
            {
                id: 'australia-it-data-science',
                name: 'IT & Data Science',
                img: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=500&h=300&fit=crop',
                alt: 'IT in Australia',
                description: 'Cloud computing infrastructure, data analytics, and cybersecurity with industry-aligned certifications.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: 'AUD 25,000 - 45,000/year',
                entryRequirements: 'IT degree, IELTS 6.5+',
                careerProspects: 'Data Analyst, IT Manager',
                universities: ['University of Melbourne', 'University of Sydney', 'Australian National University'],
                link: '/course/australia/it-data-science',
            },
            {
                id: 'australia-engineering',
                name: 'Engineering',
                img: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&h=300&fit=crop',
                alt: 'Engineering in Australia',
                description: 'Mining engineering, renewable energy systems, and civil engineering with practical industry projects.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: 'AUD 30,000 - 50,000/year',
                entryRequirements: 'Engineering Bachelor’s, IELTS 6.5+',
                careerProspects: 'Engineer, Consultant',
                universities: ['University of New South Wales', 'University of Melbourne', 'Monash University'],
                link: '/course/australia/engineering',
            },
            {
                id: 'australia-biotechnology',
                name: 'Biotechnology',
                img: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=500&h=300&fit=crop',
                alt: 'Biotechnology in Australia',
                description: 'Agricultural biotechnology, medical research innovation, and genomic studies in advanced research facilities.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: 'AUD 25,000 - 40,000/year',
                entryRequirements: 'Science degree, IELTS 6.5+',
                careerProspects: 'Biotech Researcher, Lab Technician',
                universities: ['University of Queensland', 'University of Melbourne', 'Australian National University'],
                link: '/course/australia/biotechnology',
            },
            {
                id: 'australia-nursing-physiotherapy',
                name: 'Nursing & Physiotherapy',
                img: 'https://images.unsplash.com/photo-1584614375600-7f7a3b9d0ee5?w=500&h=300&fit=crop',
                alt: 'Nursing in Australia',
                description: 'Advanced clinical skills, patient care excellence, and rehabilitation therapies in modern healthcare settings.',
                duration: '36 Months',
                qualification: 'Bachelors/Masters',
                tuition: 'AUD 20,000 - 35,000/year',
                entryRequirements: 'High School Sciences, IELTS 7.0+',
                careerProspects: 'Nurse, Physiotherapist',
                universities: ['University of Sydney', 'Monash University', 'University of Queensland'],
                link: '/course/australia/nursing-physiotherapy',
            },
            {
                id: 'australia-business-management',
                name: 'Business & Management',
                img: 'https://images.unsplash.com/photo-1552664730-d307c8eaa005?w=500&h=300&fit=crop',
                alt: 'Business in Australia',
                description: 'Strategic management principles, marketing innovation, and entrepreneurship in the Asia-Pacific business hub.',
                duration: '24 Months',
                qualification: 'MBA',
                tuition: 'AUD 40,000 - 60,000/year',
                entryRequirements: 'Bachelor’s, GMAT',
                careerProspects: 'Manager, Executive, Entrepreneur',
                universities: ['University of Melbourne', 'University of Sydney', 'Australian National University'],
                link: '/course/australia/business-management',
            },
            {
                id: 'australia-architecture',
                name: 'Architecture',
                img: 'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=500&h=300&fit=crop',
                alt: 'Architecture in Australia',
                description: 'Sustainable architectural design, urban planning innovation, and building technology in dynamic city environments.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: 'AUD 30,000 - 50,000/year',
                entryRequirements: 'Architecture degree, Portfolio',
                careerProspects: 'Architect, Designer',
                universities: ['University of Sydney', 'RMIT University', 'University of New South Wales'],
                link: '/course/australia/architecture',
            },
            {
                id: 'australia-cybersecurity',
                name: 'Cybersecurity',
                img: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=500&h=300&fit=crop',
                alt: 'Cybersecurity in Australia',
                description: 'Network security protocols, ethical hacking techniques, and digital forensics in increasingly digital economies.',
                duration: '12 Months',
                qualification: 'Masters',
                tuition: 'AUD 25,000 - 45,000/year',
                entryRequirements: 'IT degree, IELTS 6.5+',
                careerProspects: 'Security Analyst, Forensic Expert',
                universities: ['Monash University', 'Deakin University', 'Edith Cowan University'],
                link: '/course/australia/cybersecurity',
            },
            {
                id: 'australia-ai-machine-learning',
                name: 'AI & Machine Learning',
                img: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=500&h=300&fit=crop',
                alt: 'AI in Australia',
                description: 'Deep learning systems, robotics integration, and AI ethics in rapidly advancing technological landscapes.',
                duration: '18 Months',
                qualification: 'Masters',
                tuition: 'AUD 35,000 - 55,000/year',
                entryRequirements: 'CS degree, Programming',
                careerProspects: 'AI Engineer, Researcher',
                universities: ['Australian National University', 'University of Melbourne', 'University of Adelaide'],
                link: '/course/australia/ai-machine-learning',
            },
            {
                id: 'australia-psychology',
                name: 'Psychology',
                img: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=500&h=300&fit=crop',
                alt: 'Psychology in Australia',
                description: 'Clinical psychology practice, cognitive science research, and mental health services in diverse communities.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: 'AUD 25,000 - 40,000/year',
                entryRequirements: 'Psychology Bachelor’s, IELTS 7.0+',
                careerProspects: 'Psychologist, Counselor',
                universities: ['University of Melbourne', 'University of Sydney', 'University of Queensland'],
                link: '/course/australia/psychology',
            },
        ],
    },
];