export const countries = [
    {
        name: 'Germany',
        viewMoreLink: '/study-abroad/germany',
        courses: [
            {
                id: 'germany-engineering',
                name: 'Engineering',
                img: 'engrng-img.webp',
                alt: 'Engineering in Germany',
                description: 'World-renowned programs in mechanical, automotive, and electrical engineering with a focus on innovation and research.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: '€0 - €20,000/year (Public universities often free)',
                entryRequirements: 'Relevant Bachelor’s, German B2/C1 or English IELTS 6.5+',
                careerProspects: 'Engineer, R&D Specialist, Automotive Expert',
                universities: ['Technical University of Munich', 'RWTH Aachen University', 'Karlsruhe Institute of Technology'],
                link: '/course/germany/engineering',
            },
            {
                id: 'germany-computer-science',
                name: 'Computer Science',
                img: 'it-img.webp',
                alt: 'Computer Science in Germany',
                description: 'Advanced studies in AI, software development, and data science with strong industry ties like SAP and Siemens.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: '€0 - €15,000/year',
                entryRequirements: 'CS Bachelor’s, GRE optional, Programming skills',
                careerProspects: 'Software Developer, Data Scientist, IT Consultant',
                universities: ['Technical University of Munich', 'University of Freiburg', 'Ludwig Maximilian University'],
                link: '/course/germany/computer-science',
            },
            {
                id: 'germany-business-administration',
                name: 'Business Administration',
                img: 'mba-img.webp',
                alt: 'Business in Germany',
                description: 'International business, management, and economics in Europe\'s largest economy.',
                duration: '18-24 Months',
                description: 'MBA/Masters',
                tuition: '€10,000 - €30,000/year',
                entryRequirements: 'Bachelor’s, GMAT, Work experience',
                careerProspects: 'Manager, Consultant, Entrepreneur',
                universities: ['Mannheim Business School', 'WHU Otto Beisheim', 'Frankfurt School of Finance'],
                link: '/course/germany/business-administration',
            },
            {
                id: 'germany-automotive-engineering',
                name: 'Automotive Engineering',
                img: 'automotive-img.webp',
                alt: 'Automotive in Germany',
                description: 'Specialize in electric vehicles, autonomous driving, and automotive design with companies like BMW and Volkswagen.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: '€0 - €18,000/year',
                entryRequirements: 'Mechanical Engineering degree, IELTS 6.5+',
                careerProspects: 'Automotive Engineer, Designer, Researcher',
                universities: ['RWTH Aachen', 'Technical University of Munich', 'University of Stuttgart'],
                link: '/course/germany/automotive-engineering',
            },
            {
                id: 'germany-data-science-ai',
                name: 'Data Science & AI',
                img: 'data-scie-img.webp',
                alt: 'Data Science in Germany',
                description: 'Machine learning, big data, and AI ethics with cutting-edge research facilities.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: '€0 - €15,000/year',
                entryRequirements: 'STEM degree, Programming knowledge',
                careerProspects: 'Data Scientist, AI Engineer',
                universities: ['University of Tübingen', 'Technical University of Berlin', 'Max Planck Institutes'],
                link: '/course/germany/data-science-ai',
            },
            {
                id: 'germany-renewable-energy',
                name: 'Renewable Energy',
                img: 'energy-img.webp',
                alt: 'Renewable Energy in Germany',
                description: 'Sustainable energy systems, wind, solar, and environmental engineering.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: '€0 - €12,000/year',
                entryRequirements: 'Engineering/Science degree, IELTS 6.0+',
                careerProspects: 'Energy Consultant, Researcher, Engineer',
                universities: ['University of Oldenburg', 'Technical University of Berlin', 'Freiburg University'],
                link: '/course/germany/renewable-energy',
            },
            {
                id: 'germany-medicine',
                name: 'Medicine',
                img: 'medicine-ger.jpg',
                alt: 'Medicine in Germany',
                description: 'High-quality medical education with clinical training and research opportunities.',
                duration: '72 Months',
                qualification: 'State Examination',
                tuition: '€0 - €10,000/semester fees',
                entryRequirements: 'Abitur equivalent, German C1, TestAS',
                careerProspects: 'Doctor, Specialist, Researcher',
                universities: ['Heidelberg University', 'Charité Berlin', 'LMU Munich'],
                link: '/course/germany/medicine',
            },
            {
                id: 'germany-economics',
                name: 'Economics',
                img: 'economics-img.webp',
                alt: 'Economics in Germany',
                description: 'Macroeconomics, finance, and policy in a strong economic hub.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: '€0 - €20,000/year',
                entryRequirements: 'Economics Bachelor’s, GRE optional',
                careerProspects: 'Economist, Analyst, Policy Advisor',
                universities: ['University of Mannheim', 'LMU Munich', 'Humboldt University Berlin'],
                link: '/course/germany/economics',
            },
        ],
    },
    {
        name: 'UK',
        viewMoreLink: '/study-abroad/uk',
        courses: [
            {
                id: 'uk-business-management',
                name: 'Business Management',
                img: 'mba-img.webp',
                alt: 'Business management courses in UK',
                description: 'Master international business strategies, leadership, and global market dynamics with top UK universities like Oxford and Cambridge.',
                duration: '12-24 Months',
                qualification: 'Masters Degree',
                tuition: '£15,000 - £30,000/year',
                entryRequirements: 'Bachelor’s degree with 60%+, IELTS 6.5+',
                careerProspects: 'Business Analyst, Manager, Entrepreneur',
                universities: ['University of Oxford', 'London Business School', 'Imperial College London'],
                link: '/course/uk/business-management',
            },
            {
                id: 'uk-engineering',
                name: 'Engineering',
                img: 'engrng-img.webp',
                alt: 'Engineering courses in UK',
                description: 'Innovate with cutting-edge programs in mechanical, civil, and electrical engineering, focusing on sustainability and technology.',
                duration: '12-36 Months',
                qualification: 'Bachelors/Masters',
                tuition: '£18,000 - £35,000/year',
                entryRequirements: 'Relevant Bachelor’s, IELTS 6.0+',
                careerProspects: 'Engineer, Project Manager, Researcher',
                universities: ['University of Cambridge', 'Imperial College London', 'University of Manchester'],
                link: '/course/uk/engineering',
            },
            {
                id: 'uk-computer-science',
                name: 'Computer Science',
                img: 'it-img.webp',
                alt: 'Computer science in UK',
                description: 'Dive into AI, cybersecurity, software development, and data analytics with hands-on projects and industry partnerships.',
                duration: '12-24 Months',
                qualification: 'Masters Degree',
                tuition: '£20,000 - £40,000/year',
                entryRequirements: 'Computer-related degree, IELTS 6.5+',
                careerProspects: 'Software Developer, Data Scientist, IT Consultant',
                universities: ['University of Edinburgh', 'University College London', 'King’s College London'],
                link: '/course/uk/computer-science',
            },
            {
                id: 'uk-law',
                name: 'Law',
                img: 'law-img.webp',
                alt: 'Law studies in UK',
                description: 'Pursue LLB or LLM in international law, human rights, or corporate law in prestigious institutions.',
                duration: '36 Months',
                qualification: 'Bachelors/LLM',
                tuition: '£15,000 - £25,000/year',
                entryRequirements: 'Bachelor’s in any field, IELTS 7.0+',
                careerProspects: 'Lawyer, Solicitor, Legal Advisor',
                universities: ['University of Oxford', 'University of Cambridge', 'London School of Economics'],
                link: '/course/uk/law',
            },
            {
                id: 'uk-finance',
                name: 'Finance',
                img: 'Finance-img.webp',
                alt: 'Finance courses in UK',
                description: 'Excel in financial markets, investment banking, and risk management with CFA-aligned curricula.',
                duration: '12 Months',
                qualification: 'Masters',
                tuition: '£25,000 - £45,000/year',
                entryRequirements: 'Finance-related degree, GMAT optional',
                careerProspects: 'Financial Analyst, Investment Banker, Accountant',
                universities: ['London School of Economics', 'University of Warwick', 'City University London'],
                link: '/course/uk/finance',
            },
            {
                id: 'uk-architecture',
                name: 'Architecture',
                img: 'architecture-img.webp',
                alt: 'Architecture in UK',
                description: 'Design sustainable buildings and urban spaces with focus on innovation and environmental impact.',
                duration: '24-36 Months',
                qualification: 'Masters',
                tuition: '£18,000 - £30,000/year',
                entryRequirements: 'Architecture Bachelor’s, Portfolio required',
                careerProspects: 'Architect, Urban Planner, Designer',
                universities: ['Architectural Association School', 'University of Sheffield', 'Bartlett School of Architecture'],
                link: '/course/uk/architecture',
            },
            {
                id: 'uk-data-science',
                name: 'Data Science & AI',
                img: 'data-scie-img.webp',
                alt: 'Data Science in UK',
                description: 'Analyze big data, build AI models, and apply machine learning in real-world scenarios.',
                duration: '12 Months',
                qualification: 'Masters',
                tuition: '£22,000 - £38,000/year',
                entryRequirements: 'STEM degree, Programming knowledge',
                careerProspects: 'Data Scientist, AI Engineer, Analyst',
                universities: ['University of Manchester', 'University of Bristol', 'Imperial College London'],
                link: '/course/uk/data-science-ai',
            },
            {
                id: 'uk-cybersecurity',
                name: 'Cybersecurity',
                img: 'cybersecurity-uk.jpg',
                alt: 'Cybersecurity in UK',
                description: 'Protect digital assets from threats with advanced ethical hacking and security protocols.',
                duration: '12-24 Months',
                qualification: 'Masters',
                tuition: '£20,000 - £35,000/year',
                entryRequirements: 'IT degree, IELTS 6.5+',
                careerProspects: 'Cybersecurity Analyst, Ethical Hacker, Security Consultant',
                universities: ['Royal Holloway University', 'University of Southampton', 'Lancaster University'],
                link: '/course/uk/cybersecurity',
            },
            {
                id: 'uk-medicine',
                name: 'Medicine',
                img: 'medicine-uk.jpg',
                alt: 'Medicine in UK',
                description: 'World-class medical training with clinical placements and research opportunities.',
                duration: '60 Months',
                qualification: 'MBBS',
                tuition: '£30,000 - £50,000/year',
                entryRequirements: 'A-Levels in Sciences, UKCAT/BMAT',
                careerProspects: 'Doctor, Surgeon, Researcher',
                universities: ['University of Oxford', 'University of Cambridge', 'Imperial College London'],
                link: '/course/uk/medicine',
            },
        ],
    },
    {
        name: 'USA',
        viewMoreLink: '/study-abroad/usa',
        courses: [
            {
                id: 'usa-it-computer-science',
                name: 'IT & Computer Science',
                img: 'it-img.webp',
                alt: 'IT in USA',
                description: 'Explore tech hubs like Silicon Valley with programs in coding, networks, and cloud computing.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: '$30,000 - $60,000/year',
                entryRequirements: 'Bachelor’s in CS, GRE optional',
                careerProspects: 'Software Engineer, Network Admin, Tech Consultant',
                universities: ['Stanford University', 'MIT', 'Carnegie Mellon University'],
                link: '/course/usa/it-computer-science',
            },
            {
                id: 'usa-engineering',
                name: 'Engineering',
                img: 'engrng-img.webp',
                alt: 'Engineering in USA',
                description: 'Innovative STEM programs in aerospace, bioengineering, and robotics.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: '$35,000 - $70,000/year',
                entryRequirements: 'Engineering Bachelor’s, GRE',
                careerProspects: 'Engineer, R&D Specialist, Project Lead',
                universities: ['MIT', 'California Institute of Technology', 'University of California Berkeley'],
                link: '/course/usa/engineering',
            },
            {
                id: 'usa-business-administration',
                name: 'Business Administration',
                img: 'mba-img.webp',
                alt: 'MBA in USA',
                description: 'Top B-schools offering MBA with focus on entrepreneurship and global business.',
                duration: '24 Months',
                qualification: 'MBA',
                tuition: '$50,000 - $100,000/year',
                entryRequirements: 'Bachelor’s, GMAT/GRE, Work experience',
                careerProspects: 'CEO, Consultant, Manager',
                universities: ['Harvard Business School', 'Stanford GSB', 'Wharton School'],
                link: '/course/usa/business-administration',
            },
            {
                id: 'usa-finance',
                name: 'Finance',
                img: 'acc-financ-img.webp',
                alt: 'Finance in USA',
                description: 'Wall Street-inspired courses in corporate finance, fintech, and investments.',
                duration: '12 Months',
                qualification: 'Masters',
                tuition: '$40,000 - $80,000/year',
                entryRequirements: 'Finance degree, GMAT',
                careerProspects: 'Investment Banker, Financial Advisor, Trader',
                universities: ['New York University', 'University of Chicago Booth', 'Columbia Business School'],
                link: '/course/usa/finance',
            },
            {
                id: 'usa-data-science',
                name: 'Data Science',
                img: 'data-scie-img.webp',
                alt: 'Data Science in USA',
                description: 'Big data analytics, machine learning, and predictive modeling.',
                duration: '18 Months',
                qualification: 'Masters',
                tuition: '$45,000 - $75,000/year',
                entryRequirements: 'STEM background, Programming skills',
                careerProspects: 'Data Analyst, Machine Learning Engineer',
                universities: ['University of California Berkeley', 'Carnegie Mellon', 'New York University'],
                link: '/course/usa/data-science',
            },
            {
                id: 'usa-biotechnology',
                name: 'Biotechnology',
                img: 'biology-img.webp',
                alt: 'Biotech in USA',
                description: 'Biomedical research, genetic engineering, and pharma development.',
                duration: '24 Months',
                qualification: 'PhD/Masters',
                tuition: '$40,000 - $60,000/year',
                entryRequirements: 'Biology degree, GRE',
                careerProspects: 'Biotech Researcher, Lab Scientist',
                universities: ['Harvard University', 'MIT', 'University of California San Francisco'],
                link: '/course/usa/biotechnology',
            },
            {
                id: 'usa-medicine',
                name: 'Medicine',
                img: 'medicine-usa.jpg',
                alt: 'Medicine in USA',
                description: 'Advanced healthcare training with residencies and specializations.',
                duration: '48 Months',
                qualification: 'MD',
                tuition: '$50,000 - $80,000/year',
                entryRequirements: 'Bachelor’s, MCAT',
                careerProspects: 'Physician, Surgeon, Specialist',
                universities: ['Johns Hopkins University', 'Harvard Medical School', 'Mayo Clinic School'],
                link: '/course/usa/medicine',
            },
            {
                id: 'usa-ai-machine-learning',
                name: 'AI & Machine Learning',
                img: 'ai-usa.jpg',
                alt: 'AI in USA',
                description: 'Pioneer AI technologies with deep learning and neural networks.',
                duration: '12 Months',
                qualification: 'Masters',
                tuition: '$55,000 - $90,000/year',
                entryRequirements: 'CS degree, Python knowledge',
                careerProspects: 'AI Researcher, ML Engineer',
                universities: ['Stanford University', 'Carnegie Mellon', 'MIT'],
                link: '/course/usa/ai-machine-learning',
            },
        ],
    },
    {
        name: 'Canada',
        viewMoreLink: '/study-abroad/canada',
        courses: [
            {
                id: 'canada-business-administration',
                name: 'Business Administration',
                img: 'mba-img.webp',
                alt: 'Business in Canada',
                description: 'Focus on sustainable business practices and international trade.',
                duration: '24 Months',
                qualification: 'MBA',
                tuition: 'CAD 20,000 - 50,000/year',
                entryRequirements: 'Bachelor’s, GMAT, Work experience',
                careerProspects: 'Business Manager, Entrepreneur, Consultant',
                universities: ['University of Toronto Rotman', 'University of British Columbia Sauder', 'McGill University Desautels'],
                link: '/course/canada/business-administration',
            },
            {
                id: 'canada-engineering',
                name: 'Engineering',
                img: 'engrng-img.webp',
                alt: 'Engineering in Canada',
                description: 'Programs in mining, environmental, and software engineering.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: 'CAD 25,000 - 45,000/year',
                entryRequirements: 'Engineering degree, IELTS 6.5+',
                careerProspects: 'Engineer, Project Manager',
                universities: ['University of Toronto', 'University of Waterloo', 'University of British Columbia'],
                link: '/course/canada/engineering',
            },
            {
                id: 'canada-computer-science',
                name: 'Computer Science',
                img: 'it-img.webp',
                alt: 'Computer Science in Canada',
                description: 'AI, cybersecurity, and big data with co-op opportunities.',
                duration: '12-24 Months',
                qualification: 'Masters',
                tuition: 'CAD 20,000 - 40,000/year',
                entryRequirements: 'CS degree, GRE optional',
                careerProspects: 'Developer, Analyst, Tech Specialist',
                universities: ['University of Toronto', 'University of Waterloo', 'University of Montreal'],
                link: '/course/canada/computer-science',
            },
            {
                id: 'canada-hospitality-tourism',
                name: 'Hospitality & Tourism',
                img: 'hospitality-img.webp',
                alt: 'Hospitality in Canada',
                description: 'Hotel management, event planning, and sustainable tourism.',
                duration: '24 Months',
                qualification: 'Diploma/Masters',
                tuition: 'CAD 15,000 - 30,000/year',
                entryRequirements: 'High School, IELTS 6.0+',
                careerProspects: 'Hotel Manager, Tour Operator',
                universities: ['George Brown College', 'Vancouver Island University', 'Ryerson University'],
                link: '/course/canada/hospitality-tourism',
            },
            {
                id: 'canada-education',
                name: 'Education',
                img: 'educ-img.webp',
                alt: 'Education in Canada',
                description: 'Teacher training, educational leadership, and pedagogy.',
                duration: '12 Months',
                qualification: 'Masters',
                tuition: 'CAD 18,000 - 35,000/year',
                entryRequirements: 'Bachelor’s in Education, Teaching experience',
                careerProspects: 'Teacher, Administrator, Curriculum Developer',
                universities: ['University of British Columbia', 'University of Toronto OISE', 'University of Alberta'],
                link: '/course/canada/education',
            },
            {
                id: 'canada-environmental-science',
                name: 'Environmental Science',
                img: 'envr-scie-img.webp',
                alt: 'Environmental Science in Canada',
                description: 'Climate change, conservation, and resource management.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: 'CAD 20,000 - 40,000/year',
                entryRequirements: 'Science degree, IELTS 6.5+',
                careerProspects: 'Environmental Consultant, Researcher',
                universities: ['University of Waterloo', 'Dalhousie University', 'University of Guelph'],
                link: '/course/canada/environmental-science',
            },
            {
                id: 'canada-data-science-ai',
                name: 'Data Science & AI',
                img: 'data-scie-img.webp',
                alt: 'Data Science in Canada',
                description: 'Machine learning, data visualization, and predictive analytics.',
                duration: '12 Months',
                qualification: 'Masters',
                tuition: 'CAD 25,000 - 45,000/year',
                entryRequirements: 'STEM degree, Programming',
                careerProspects: 'Data Scientist, AI Specialist',
                universities: ['University of Toronto', 'University of British Columbia', 'McGill University'],
                link: '/course/canada/data-science-ai',
            },
            {
                id: 'canada-law',
                name: 'Law',
                img: 'law-img.webp',
                alt: 'Law in Canada',
                description: 'JD programs with focus on Canadian and international law.',
                duration: '36 Months',
                qualification: 'JD',
                tuition: 'CAD 30,000 - 50,000/year',
                entryRequirements: 'Bachelor’s, LSAT',
                careerProspects: 'Lawyer, Judge, Legal Consultant',
                universities: ['University of Toronto', 'McGill University', 'University of British Columbia'],
                link: '/course/canada/law',
            },
            {
                id: 'canada-nursing',
                name: 'Nursing',
                img: 'healthcare-img.webp',
                alt: 'Nursing in Canada',
                description: 'Clinical practice, public health, and nursing leadership.',
                duration: '48 Months',
                qualification: 'BScN',
                tuition: 'CAD 20,000 - 40,000/year',
                entryRequirements: 'High School Sciences, IELTS 7.0+',
                careerProspects: 'Registered Nurse, Nurse Practitioner',
                universities: ['University of Alberta', 'University of Toronto', 'McMaster University'],
                link: '/course/canada/nursing',
            },
        ],
    },
    {
        name: 'Australia',
        viewMoreLink: '/study-abroad/australia',
        courses: [
            {
                id: 'australia-it-data-science',
                name: 'IT & Data Science',
                img: 'it-img.webp',
                alt: 'IT in Australia',
                description: 'Cloud computing, data analytics, and cybersecurity with industry certifications.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: 'AUD 25,000 - 45,000/year',
                entryRequirements: 'IT degree, IELTS 6.5+',
                careerProspects: 'Data Analyst, IT Manager',
                universities: ['University of Melbourne', 'University of Sydney', 'Australian National University'],
                link: '/course/australia/it-data-science',
            },
            {
                id: 'australia-engineering',
                name: 'Engineering',
                img: 'engrng-img.webp',
                alt: 'Engineering in Australia',
                description: 'Mining, renewable energy, and civil engineering with practical projects.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: 'AUD 30,000 - 50,000/year',
                entryRequirements: 'Engineering Bachelor’s, IELTS 6.5+',
                careerProspects: 'Engineer, Consultant',
                universities: ['University of New South Wales', 'University of Melbourne', 'Monash University'],
                link: '/course/australia/engineering',
            },
            {
                id: 'australia-biotechnology',
                name: 'Biotechnology',
                img: 'agriculture-img.webp',
                alt: 'Biotechnology in Australia',
                description: 'Agricultural biotech, medical research, and genomics.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: 'AUD 25,000 - 40,000/year',
                entryRequirements: 'Science degree, IELTS 6.5+',
                careerProspects: 'Biotech Researcher, Lab Technician',
                universities: ['University of Queensland', 'University of Melbourne', 'Australian National University'],
                link: '/course/australia/biotechnology',
            },
            {
                id: 'australia-nursing-physiotherapy',
                name: 'Nursing & Physiotherapy',
                img: 'healthcare-img.webp',
                alt: 'Nursing in Australia',
                description: 'Clinical skills, patient care, and rehabilitation therapies.',
                duration: '36 Months',
                qualification: 'Bachelors/Masters',
                tuition: 'AUD 20,000 - 35,000/year',
                entryRequirements: 'High School Sciences, IELTS 7.0+',
                careerProspects: 'Nurse, Physiotherapist',
                universities: ['University of Sydney', 'Monash University', 'University of Queensland'],
                link: '/course/australia/nursing-physiotherapy',
            },
            {
                id: 'australia-business-management',
                name: 'Business & Management',
                img: 'mba-img.webp',
                alt: 'Business in Australia',
                description: 'Strategic management, marketing, and entrepreneurship.',
                duration: '24 Months',
                qualification: 'MBA',
                tuition: 'AUD 40,000 - 60,000/year',
                entryRequirements: 'Bachelor’s, GMAT',
                careerProspects: 'Manager, Executive, Entrepreneur',
                universities: ['University of Melbourne', 'University of Sydney', 'Australian National University'],
                link: '/course/australia/business-management',
            },
            {
                id: 'australia-architecture',
                name: 'Architecture',
                img: 'architecture-img.webp',
                alt: 'Architecture in Australia',
                description: 'Sustainable design, urban planning, and architectural technology.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: 'AUD 30,000 - 50,000/year',
                entryRequirements: 'Architecture degree, Portfolio',
                careerProspects: 'Architect, Designer',
                universities: ['University of Sydney', 'RMIT University', 'University of New South Wales'],
                link: '/course/australia/architecture',
            },
            {
                id: 'australia-cybersecurity',
                name: 'Cybersecurity',
                img: 'cybersecurity-australia.jpg',
                alt: 'Cybersecurity in Australia',
                description: 'Network security, ethical hacking, and digital forensics.',
                duration: '12 Months',
                qualification: 'Masters',
                tuition: 'AUD 25,000 - 45,000/year',
                entryRequirements: 'IT degree, IELTS 6.5+',
                careerProspects: 'Security Analyst, Forensic Expert',
                universities: ['Monash University', 'Deakin University', 'Edith Cowan University'],
                link: '/course/australia/cybersecurity',
            },
            {
                id: 'australia-ai-machine-learning',
                name: 'AI & Machine Learning',
                img: 'ai-australia.jpg',
                alt: 'AI in Australia',
                description: 'Deep learning, robotics, and AI ethics.',
                duration: '18 Months',
                qualification: 'Masters',
                tuition: 'AUD 35,000 - 55,000/year',
                entryRequirements: 'CS degree, Programming',
                careerProspects: 'AI Engineer, Researcher',
                universities: ['Australian National University', 'University of Melbourne', 'University of Adelaide'],
                link: '/course/australia/ai-machine-learning',
            },
            {
                id: 'australia-psychology',
                name: 'Psychology',
                img: 'psychology-australia.jpg',
                alt: 'Psychology in Australia',
                description: 'Clinical psychology, cognitive science, and mental health.',
                duration: '24 Months',
                qualification: 'Masters',
                tuition: 'AUD 25,000 - 40,000/year',
                entryRequirements: 'Psychology Bachelor’s, IELTS 7.0+',
                careerProspects: 'Psychologist, Counselor',
                universities: ['University of Melbourne', 'University of Sydney', 'University of Queensland'],
                link: '/course/australia/psychology',
            },
        ],
    },
];