export const countries = [
    {
        name: "United States",
        flag: "https://flagcdn.com/us.svg",
        capital: "Washington, D.C.",
        language: "English",
        currency: "USD ($)",
        details: "Home to world-renowned universities offering diverse programs and excellent research opportunities with state-of-the-art facilities and global recognition.",
        rank: "Top Ranked Globally",
        programs: "5000+ Programs",
        topRanked: "25",
        students: "1.2M+",
        programsCount: "5000+",
        universities: [
            {
                name: "Harvard University",
                rank: "3",
                location: "Cambridge, MA",
                type: "Private Ivy League",
                acceptanceRate: "5%",
                internationalStudents: "22%",
                scholarships: "Generous Available",
                founded: "1636",
                totalStudents: "22,000",
                campus: "Urban",
                language: "English",
                motto: "Veritas (Truth)",
                programs: [
                    "Computer Science",
                    "Business Administration (MBA)",
                    "Law (JD)",
                    "Medicine (MD)",
                    "Engineering & Applied Sciences",
                    "Political Science",
                    "Economics",
                    "Psychology"
                ],
                detailedDescription: "Harvard University is a private Ivy League research university in Cambridge, Massachusetts. Founded in 1636, it is the oldest institution of higher learning in the United States and among the most prestigious in the world. The university has produced numerous Nobel laureates, Rhodes Scholars, and heads of state.",
                popularPrograms: "Law, Business, Medicine, Computer Science",
                employmentRate: "95%",
                studentFacultyRatio: "7:1",
                notableAlumni: "Barack Obama, Mark Zuckerberg, Bill Gates"
            },
            {
                name: "Stanford University",
                rank: "5",
                location: "Stanford, CA",
                type: "Private Research",
                acceptanceRate: "4%",
                internationalStudents: "24%",
                scholarships: "Need-based",
                founded: "1885",
                totalStudents: "17,000",
                campus: "Suburban",
                language: "English",
                motto: "Die Luft der Freiheit weht (The wind of freedom blows)",
                programs: [
                    "Computer Science",
                    "Electrical Engineering",
                    "Business Management",
                    "Mechanical Engineering",
                    "Bioengineering",
                    "Design Thinking",
                    "Artificial Intelligence"
                ],
                detailedDescription: "Stanford University is a private research university known for its entrepreneurial character and proximity to Silicon Valley. It has been credited with fueling the growth of the technology industry in the region and beyond.",
                popularPrograms: "Engineering, Computer Science, Business",
                employmentRate: "94%",
                studentFacultyRatio: "5:1",
                notableAlumni: "Larry Page, Sergey Brin, Elon Musk"
            },
            {
                name: "MIT",
                rank: "1",
                location: "Cambridge, MA",
                type: "Private Research",
                acceptanceRate: "7%",
                internationalStudents: "29%",
                scholarships: "Merit-based",
                founded: "1861",
                totalStudents: "11,000",
                campus: "Urban",
                language: "English",
                motto: "Mens et Manus (Mind and Hand)",
                programs: [
                    "Computer Science & Engineering",
                    "Mechanical Engineering",
                    "Physics",
                    "Mathematics",
                    "Architecture",
                    "Business Analytics",
                    "Robotics"
                ],
                detailedDescription: "The Massachusetts Institute of Technology is a private land-grant research university known for its strong emphasis on scientific and technological research. It has played a key role in the development of modern technology and science.",
                popularPrograms: "Engineering, Computer Science, Physics",
                employmentRate: "96%",
                studentFacultyRatio: "3:1",
                notableAlumni: "Buzz Aldrin, Kofi Annan, Richard Feynman"
            },
            {
                name: "California Institute of Technology",
                rank: "6",
                location: "Pasadena, CA",
                type: "Private Research",
                acceptanceRate: "6%",
                internationalStudents: "33%",
                scholarships: "Available",
                founded: "1891",
                totalStudents: "2,200",
                campus: "Suburban",
                language: "English",
                motto: "The truth shall make you free",
                programs: [
                    "Physics",
                    "Chemistry",
                    "Biology",
                    "Engineering",
                    "Mathematics",
                    "Astronomy",
                    "Geological Sciences"
                ],
                detailedDescription: "Caltech is a world-renowned science and engineering institute that marshals some of the world's brightest minds and most innovative tools to address fundamental scientific questions and pressing societal challenges.",
                popularPrograms: "Physics, Engineering, Chemistry",
                employmentRate: "93%",
                studentFacultyRatio: "3:1",
                notableAlumni: "Gordon Moore, Frank Capra, Harrison Schmitt"
            }
        ]
    },
    {
        name: "United Kingdom",
        flag: "https://flagcdn.com/gb.svg",
        capital: "London",
        language: "English",
        currency: "GBP (£)",
        details: "Renowned for its historic universities and rigorous academic standards, the UK offers world-class education with strong international connections and research opportunities.",
        rank: "Top 10 Globally",
        programs: "3000+ Programs",
        topRanked: "18",
        students: "600K+",
        programsCount: "3500+",
        universities: [
            {
                name: "University of Oxford",
                rank: "2",
                location: "Oxford, England",
                type: "Public Research",
                acceptanceRate: "17%",
                internationalStudents: "43%",
                scholarships: "Rhodes & Others",
                founded: "1096",
                totalStudents: "24,000",
                campus: "Collegiate",
                language: "English",
                motto: "Dominus illuminatio mea (The Lord is my light)",
                programs: [
                    "PPE (Philosophy, Politics, Economics)",
                    "Medicine",
                    "Law",
                    "Computer Science",
                    "History",
                    "English Literature",
                    "Mathematics"
                ],
                detailedDescription: "The University of Oxford is a collegiate research university in Oxford, England. There is evidence of teaching as early as 1096, making it the oldest university in the English-speaking world and the world's second-oldest university in continuous operation.",
                popularPrograms: "PPE, Law, Medicine, Humanities",
                employmentRate: "92%",
                studentFacultyRatio: "11:1",
                notableAlumni: "Stephen Hawking, Margaret Thatcher, Bill Clinton"
            },
            {
                name: "University of Cambridge",
                rank: "4",
                location: "Cambridge, England",
                type: "Public Research",
                acceptanceRate: "21%",
                internationalStudents: "37%",
                scholarships: "Gates Cambridge",
                founded: "1209",
                totalStudents: "20,000",
                campus: "Collegiate",
                language: "English",
                motto: "Hinc lucem et pocula sacra (From here, light and sacred draughts)",
                programs: [
                    "Natural Sciences",
                    "Engineering",
                    "Mathematics",
                    "Medicine",
                    "Computer Science",
                    "Economics",
                    "Architecture"
                ],
                detailedDescription: "The University of Cambridge is a collegiate research university that has nurtured some of the greatest minds in history. It is known for its exceptional teaching and research across sciences and humanities.",
                popularPrograms: "Natural Sciences, Engineering, Mathematics",
                employmentRate: "94%",
                studentFacultyRatio: "11:1",
                notableAlumni: "Isaac Newton, Charles Darwin, Stephen Fry"
            },
            {
                name: "Imperial College London",
                rank: "8",
                location: "London, England",
                type: "Public Research",
                acceptanceRate: "14%",
                internationalStudents: "60%",
                scholarships: "President's Scholarships",
                founded: "1907",
                totalStudents: "19,000",
                campus: "Urban",
                language: "English",
                motto: "Scientia imperii decus et tutamen (Scientific knowledge, the crowning glory and the safeguard of the empire)",
                programs: [
                    "Mechanical Engineering",
                    "Medicine",
                    "Computing",
                    "Business",
                    "Aeronautics",
                    "Bioengineering",
                    "Chemistry"
                ],
                detailedDescription: "Imperial College London is a world-class university with a mission to benefit society through excellence in science, engineering, medicine and business. It is consistently ranked among the top universities globally.",
                popularPrograms: "Engineering, Medicine, Business",
                employmentRate: "95%",
                studentFacultyRatio: "11:1",
                notableAlumni: "Alexander Fleming, H.G. Wells, Brian May"
            },
            {
                name: "London School of Economics",
                rank: "45",
                location: "London, England",
                type: "Public Research",
                acceptanceRate: "9%",
                internationalStudents: "70%",
                scholarships: "Available",
                founded: "1895",
                totalStudents: "11,000",
                campus: "Urban",
                language: "English",
                motto: "Rerum cognoscere causas (To understand the causes of things)",
                programs: [
                    "Economics",
                    "International Relations",
                    "Law",
                    "Management",
                    "Finance",
                    "Political Science",
                    "Sociology"
                ],
                detailedDescription: "LSE is a world-leading social science university specializing in a wide range of social science disciplines, including economics, politics, sociology, law, and anthropology.",
                popularPrograms: "Economics, Politics, Law",
                employmentRate: "91%",
                studentFacultyRatio: "12:1",
                notableAlumni: "John F. Kennedy, George Soros, Mick Jagger"
            }
        ]
    },
    {
        name: "Canada",
        flag: "https://flagcdn.com/ca.svg",
        capital: "Ottawa",
        language: "English, French",
        currency: "CAD ($)",
        details: "Canada offers high-quality education with affordable tuition fees and excellent post-study work opportunities in a multicultural and welcoming environment.",
        rank: "Top 15 Globally",
        programs: "2500+ Programs",
        topRanked: "12",
        students: "450K+",
        programsCount: "2800+",
        universities: [
            {
                name: "University of Toronto",
                rank: "21",
                location: "Toronto, Ontario",
                type: "Public Research",
                acceptanceRate: "43%",
                internationalStudents: "25%",
                scholarships: "Lester B. Pearson",
                founded: "1827",
                totalStudents: "90,000",
                campus: "Urban",
                language: "English",
                motto: "Velut arbor ævo (As a tree through the ages)",
                programs: [
                    "Computer Science",
                    "Engineering",
                    "Medicine",
                    "Business",
                    "Humanities",
                    "Social Sciences",
                    "Life Sciences"
                ],
                detailedDescription: "The University of Toronto is a global leader in research and teaching, consistently ranked among the top 20 universities in the world. It offers a vast array of undergraduate and graduate programs across three campuses.",
                popularPrograms: "Computer Science, Engineering, Medicine",
                employmentRate: "89%",
                studentFacultyRatio: "25:1",
                notableAlumni: "Lester B. Pearson, Margaret Atwood, Frederick Banting"
            },
            {
                name: "University of British Columbia",
                rank: "34",
                location: "Vancouver, British Columbia",
                type: "Public Research",
                acceptanceRate: "52%",
                internationalStudents: "30%",
                scholarships: "International Scholars",
                founded: "1908",
                totalStudents: "66,000",
                campus: "Urban & Suburban",
                language: "English",
                motto: "Tuum est (It is yours)",
                programs: [
                    "Business",
                    "Engineering",
                    "Forestry",
                    "Computer Science",
                    "Marine Biology",
                    "International Relations",
                    "Environmental Science"
                ],
                detailedDescription: "UBC is a global centre for research and teaching, consistently ranked among the top 20 public universities in the world. The university embraces innovation and challenges the status quo.",
                popularPrograms: "Business, Engineering, Environmental Science",
                employmentRate: "90%",
                studentFacultyRatio: "18:1",
                notableAlumni: "Justin Trudeau, Michael Smith, Robert Mundell"
            },
            {
                name: "McGill University",
                rank: "30",
                location: "Montreal, Quebec",
                type: "Public Research",
                acceptanceRate: "46%",
                internationalStudents: "32%",
                scholarships: "Entrance Scholarships",
                founded: "1821",
                totalStudents: "40,000",
                campus: "Urban",
                language: "English",
                motto: "Grandescunt aucta labore (By work, all things increase and grow)",
                programs: [
                    "Medicine",
                    "Law",
                    "Engineering",
                    "Management",
                    "Arts",
                    "Science",
                    "Music"
                ],
                detailedDescription: "McGill University is one of Canada's best-known institutions of higher learning and one of the leading universities in the world. With students coming from over 150 countries, it is the most internationally diverse medical-doctoral university in Canada.",
                popularPrograms: "Medicine, Law, Engineering",
                employmentRate: "92%",
                studentFacultyRatio: "16:1",
                notableAlumni: "William Shatner, Leonard Cohen, John Abbott"
            }
        ]
    },
    {
        name: "Australia",
        flag: "https://flagcdn.com/au.svg",
        capital: "Canberra",
        language: "English",
        currency: "AUD ($)",
        details: "Australia offers world-class education with excellent research facilities and a high quality of life, making it a popular destination for international students.",
        rank: "Top 20 Globally",
        programs: "1800+ Programs",
        topRanked: "15",
        students: "700K+",
        programsCount: "2000+",
        universities: [
            {
                name: "University of Melbourne",
                rank: "33",
                location: "Melbourne, Victoria",
                type: "Public Research",
                acceptanceRate: "70%",
                internationalStudents: "42%",
                scholarships: "Melbourne Scholarships",
                founded: "1853",
                totalStudents: "52,000",
                campus: "Urban",
                language: "English",
                motto: "Postera crescam laude (We grow in the esteem of future generations)",
                programs: [
                    "Business",
                    "Medicine",
                    "Law",
                    "Engineering",
                    "Arts",
                    "Science",
                    "Architecture"
                ],
                detailedDescription: "The University of Melbourne is a public research university located in Melbourne, Australia. Founded in 1853, it is Australia's second oldest university and the oldest in Victoria.",
                popularPrograms: "Business, Medicine, Law",
                employmentRate: "88%",
                studentFacultyRatio: "12:1",
                notableAlumni: "Julia Gillard, Peter Doherty, Germaine Greer"
            },
            {
                name: "Australian National University",
                rank: "38",
                location: "Canberra, ACT",
                type: "Public Research",
                acceptanceRate: "35%",
                internationalStudents: "37%",
                scholarships: "ANU Chancellor's",
                founded: "1946",
                totalStudents: "20,000",
                campus: "Urban",
                language: "English",
                motto: "Naturam primum cognoscere rerum (First to learn the nature of things)",
                programs: [
                    "Political Science",
                    "International Relations",
                    "Science",
                    "Engineering",
                    "Business",
                    "Law",
                    "Arts"
                ],
                detailedDescription: "ANU is a world-leading university in Australia's capital city, Canberra. Our location points to our unique history, ties to the Australian Government and special standing as a resource for the Australian people.",
                popularPrograms: "Political Science, International Relations, Science",
                employmentRate: "90%",
                studentFacultyRatio: "15:1",
                notableAlumni: "Kevin Rudd, Bob Hawke, Brian Schmidt"
            },
            {
                name: "University of Sydney",
                rank: "41",
                location: "Sydney, New South Wales",
                type: "Public Research",
                acceptanceRate: "30%",
                internationalStudents: "43%",
                scholarships: "Sydney Scholars",
                founded: "1850",
                totalStudents: "61,000",
                campus: "Urban",
                language: "English",
                motto: "Sidere mens eadem mutato (The stars change, the mind remains the same)",
                programs: [
                    "Medicine",
                    "Law",
                    "Engineering",
                    "Business",
                    "Arts & Social Sciences",
                    "Science",
                    "Architecture"
                ],
                detailedDescription: "The University of Sydney is a public research university in Sydney, Australia. Founded in 1850, it is Australia's first university and is regarded as one of the world's leading universities.",
                popularPrograms: "Medicine, Law, Engineering",
                employmentRate: "87%",
                studentFacultyRatio: "14:1",
                notableAlumni: "Malcolm Turnbull, John H. Howard, Dame Marie Bashir"
            }
        ]
    },
    {
        name: "Germany",
        flag: "https://flagcdn.com/de.svg",
        capital: "Berlin",
        language: "German",
        currency: "EUR (€)",
        details: "Germany offers tuition-free public education with world-class engineering programs. 17 Technical Universities (TUs), 100+ Universities of Applied Sciences (UAS), and dual study options make it ideal for practical and research-oriented engineering education.",
        rank: "Top 25 Globally",
        programs: "2600+ Engineering Programs",
        topRanked: "22",
        students: "400K+",
        programsCount: "2800+",
        tuition: "No tuition fees (only €150–€350/semester admin fee)",
        postStudyWork: "18 months job search visa",
        workWhileStudy: "120 full days or 240 half days/year",
        engineeringFocus: true,
        universities: [
            // === 17 TECHNICAL UNIVERSITIES (TUs) - FULL DETAILS ===
            {
                name: "RWTH Aachen University",
                rank: "99",
                location: "Aachen, North Rhine-Westphalia",
                type: "Public Research (TU)",
                acceptanceRate: "10%",
                internationalStudents: "26%",
                scholarships: "DAAD, RWTH Excellence",
                founded: "1870",
                totalStudents: "45,000",
                campus: "Urban",
                language: "German, English",
                motto: "Thinking the Future",
                programs: [
                    "Mechanical Engineering",
                    "Electrical Engineering",
                    "Automotive Engineering",
                    "Materials Science",
                    "Civil Engineering",
                    "Computer Science",
                    "Robotics & AI"
                ],
                detailedDescription: "RWTH Aachen is one of Europe’s leading technical universities and part of the TU9 alliance. Known for industry collaboration and innovation in engineering.",
                popularPrograms: "Mechanical Engineering, Automotive, Materials",
                employmentRate: "95%",
                studentFacultyRatio: "18:1",
                notableAlumni: "B.J. Habibie, Hugo Junkers"
            },
            {
                name: "Technical University of Berlin",
                rank: "147",
                location: "Berlin",
                type: "Public Research (TU)",
                acceptanceRate: "15%",
                internationalStudents: "22%",
                scholarships: "DAAD, TU Berlin",
                founded: "1879",
                totalStudents: "35,000",
                campus: "Urban",
                language: "German, English",
                motto: "We have the ideas for the future",
                programs: [
                    "Architecture",
                    "Civil Engineering",
                    "Mechanical Engineering",
                    "Computer Science",
                    "Sustainable Energy",
                    "Transportation Systems"
                ],
                detailedDescription: "TU Berlin is a TU9 member located in Germany’s startup capital. Strong focus on innovation and sustainability.",
                popularPrograms: "Engineering, Architecture, Energy",
                employmentRate: "92%",
                studentFacultyRatio: "20:1",
                notableAlumni: "Konrad Zuse, Wernher von Braun"
            },
            {
                name: "Technical University of Braunschweig",
                rank: "351",
                location: "Braunschweig, Lower Saxony",
                type: "Public Research (TU)",
                acceptanceRate: "20%",
                internationalStudents: "18%",
                scholarships: "DAAD",
                founded: "1745",
                totalStudents: "20,000",
                campus: "Urban",
                language: "German, English",
                motto: "Future through knowledge",
                programs: [
                    "Aerospace Engineering",
                    "Mechanical Engineering",
                    "Pharmacy",
                    "Mobility Systems",
                    "Biotechnology"
                ],
                detailedDescription: "One of the oldest TUs in Germany, known for aerospace and mobility research.",
                popularPrograms: "Aerospace, Mechanical Engineering",
                employmentRate: "90%",
                studentFacultyRatio: "22:1",
                notableAlumni: "Carl Friedrich Gauss, Richard Dedekind"
            },
            {
                name: "Technical University of Chemnitz",
                rank: "601",
                location: "Chemnitz, Saxony",
                type: "Public Research (TU)",
                acceptanceRate: "25%",
                internationalStudents: "15%",
                scholarships: "DAAD",
                founded: "1836",
                totalStudents: "10,000",
                campus: "Urban",
                language: "German, English",
                motto: "Smart Systems",
                programs: [
                    "Automotive Engineering",
                    "Textile Technology",
                    "Microsystems",
                    "Sensor Technology"
                ],
                detailedDescription: "Specializes in smart systems, automotive, and textile engineering.",
                popularPrograms: "Automotive, Microsystems",
                employmentRate: "88%",
                studentFacultyRatio: "25:1",
                notableAlumni: "N/A"
            },
            {
                name: "Technical University of Clausthal",
                rank: "801",
                location: "Clausthal-Zellerfeld, Lower Saxony",
                type: "Public Research (TU)",
                acceptanceRate: "22%",
                internationalStudents: "20%",
                scholarships: "DAAD",
                founded: "1775",
                totalStudents: "4,000",
                campus: "Rural",
                language: "German, English",
                motto: "Resources and Energy",
                programs: [
                    "Mining Engineering",
                    "Energy Technology",
                    "Materials Science",
                    "Process Engineering"
                ],
                detailedDescription: "One of the smallest TUs, focused on mining, energy, and sustainable resources.",
                popularPrograms: "Energy, Materials",
                employmentRate: "90%",
                studentFacultyRatio: "15:1",
                notableAlumni: "N/A"
            },
            {
                name: "Brandenburg Technical University of Cottbus-Senftenberg",
                rank: "901",
                location: "Cottbus, Brandenburg",
                type: "Public Research (TU)",
                acceptanceRate: "30%",
                internationalStudents: "25%",
                scholarships: "DAAD",
                founded: "2013",
                totalStudents: "7,000",
                campus: "Urban",
                language: "German, English",
                motto: "Energy and Environment",
                programs: [
                    "Environmental Engineering",
                    "Power Engineering",
                    "Civil Engineering",
                    "Biotechnology"
                ],
                detailedDescription: "Focuses on energy transition and environmental technology.",
                popularPrograms: "Environmental Engineering, Power",
                employmentRate: "87%",
                studentFacultyRatio: "20:1",
                notableAlumni: "N/A"
            },
            {
                name: "Technical University of Darmstadt",
                rank: "251",
                location: "Darmstadt, Hesse",
                type: "Public Research (TU)",
                acceptanceRate: "18%",
                internationalStudents: "20%",
                scholarships: "DAAD",
                founded: "1877",
                totalStudents: "25,000",
                campus: "Urban",
                language: "German, English",
                motto: "Man and Technology",
                programs: [
                    "Mechanical Engineering",
                    "Electrical Engineering",
                    "Computer Science",
                    "AI",
                    "Architecture"
                ],
                detailedDescription: "TU9 member known for AI, computer science, and engineering.",
                popularPrograms: "AI, Engineering",
                employmentRate: "91%",
                studentFacultyRatio: "21:1",
                notableAlumni: "Gerhard Ertl"
            },
            {
                name: "Technical University of Dortmund",
                rank: "801",
                location: "Dortmund, North Rhine-Westphalia",
                type: "Public Research (TU)",
                acceptanceRate: "25%",
                internationalStudents: "16%",
                scholarships: "DAAD",
                founded: "1968",
                totalStudents: "34,000",
                campus: "Urban",
                language: "German, English",
                motto: "Logistics and Production",
                programs: [
                    "Logistics",
                    "Mechanical Engineering",
                    "Chemical Engineering",
                    "Computer Science"
                ],
                detailedDescription: "Strong in logistics, production, and industrial engineering.",
                popularPrograms: "Logistics, Mechanical",
                employmentRate: "89%",
                studentFacultyRatio: "23:1",
                notableAlumni: "N/A"
            },
            {
                name: "Technical University of Dresden",
                rank: "200",
                location: "Dresden, Saxony",
                type: "Public Research (TU)",
                acceptanceRate: "14%",
                internationalStudents: "18%",
                scholarships: "DAAD",
                founded: "1828",
                totalStudents: "32,000",
                campus: "Urban",
                language: "German, English",
                motto: "Knowledge builds bridges",
                programs: [
                    "Microelectronics",
                    "Materials Science",
                    "Civil Engineering",
                    "Biotechnology"
                ],
                detailedDescription: "Large TU9 member known for microelectronics and biotech.",
                popularPrograms: "Microelectronics, Materials",
                employmentRate: "90%",
                studentFacultyRatio: "22:1",
                notableAlumni: "Manfred von Ardenne"
            },
            {
                name: "Technical University of Bergakademie Freiberg",
                rank: "1001",
                location: "Freiberg, Saxony",
                type: "Public Research (TU)",
                acceptanceRate: "30%",
                internationalStudents: "22%",
                scholarships: "DAAD",
                founded: "1765",
                totalStudents: "4,000",
                campus: "Small Town",
                language: "German, English",
                motto: "Mining and Geo-Sciences",
                programs: [
                    "Mining Engineering",
                    "Geology",
                    "Materials Science",
                    "Energy Systems"
                ],
                detailedDescription: "The oldest mining university in the world.",
                popularPrograms: "Mining, Geology",
                employmentRate: "92%",
                studentFacultyRatio: "12:1",
                notableAlumni: "Alexander von Humboldt"
            },
            {
                name: "Hamburg University of Technology",
                rank: "601",
                location: "Hamburg",
                type: "Public Research (TU)",
                acceptanceRate: "20%",
                internationalStudents: "20%",
                scholarships: "DAAD",
                founded: "1978",
                totalStudents: "7,500",
                campus: "Urban",
                language: "German, English",
                motto: "Maritime and Process Engineering",
                programs: [
                    "Process Engineering",
                    "Shipbuilding",
                    "Logistics",
                    "Biotechnology"
                ],
                detailedDescription: "Focus on maritime, process, and logistics engineering.",
                popularPrograms: "Process, Maritime",
                employmentRate: "91%",
                studentFacultyRatio: "18:1",
                notableAlumni: "N/A"
            },
            {
                name: "Technical University of Hannover",
                rank: "501",
                location: "Hannover, Lower Saxony",
                type: "Public Research (TU)",
                acceptanceRate: "18%",
                internationalStudents: "19%",
                scholarships: "DAAD",
                founded: "1831",
                totalStudents: "30,000",
                campus: "Urban",
                language: "German, English",
                motto: "Mechanical and Production",
                programs: [
                    "Mechanical Engineering",
                    "Production Technology",
                    "Geodesy",
                    "Architecture"
                ],
                detailedDescription: "Strong in mechanical and production engineering.",
                popularPrograms: "Mechanical, Production",
                employmentRate: "90%",
                studentFacultyRatio: "20:1",
                notableAlumni: "N/A"
            },
            {
                name: "Technical University of Ilmenau",
                rank: "901",
                location: "Ilmenau, Thuringia",
                type: "Public Research (TU)",
                acceptanceRate: "25%",
                internationalStudents: "20%",
                scholarships: "DAAD",
                founded: "1894",
                totalStudents: "5,500",
                campus: "Small Town",
                language: "German, English",
                motto: "Mechatronics",
                programs: [
                    "Mechatronics",
                    "Media Technology",
                    "Electrical Engineering",
                    "Biomedical Engineering"
                ],
                detailedDescription: "Specializes in mechatronics and media technology.",
                popularPrograms: "Mechatronics",
                employmentRate: "89%",
                studentFacultyRatio: "16:1",
                notableAlumni: "N/A"
            },
            {
                name: "Technical University of Kaiserslautern",
                rank: "801",
                location: "Kaiserslautern, Rhineland-Palatinate",
                type: "Public Research (TU)",
                acceptanceRate: "22%",
                internationalStudents: "18%",
                scholarships: "DAAD",
                founded: "1970",
                totalStudents: "14,000",
                campus: "Urban",
                language: "German, English",
                motto: "Distance Learning and Tech",
                programs: [
                    "Computer Science",
                    "Electrical Engineering",
                    "Distance Education",
                    "Construction Engineering"
                ],
                detailedDescription: "Leader in distance learning and technical education.",
                popularPrograms: "Computer Science, Distance Learning",
                employmentRate: "88%",
                studentFacultyRatio: "19:1",
                notableAlumni: "N/A"
            },
            {
                name: "Karlsruhe Institute of Technology",
                rank: "102",
                location: "Karlsruhe, Baden-Württemberg",
                type: "Public Research (TU)",
                acceptanceRate: "12%",
                internationalStudents: "25%",
                scholarships: "DAAD, KIT",
                founded: "1825",
                totalStudents: "24,000",
                campus: "Urban",
                language: "German, English",
                motto: "Veritas et Scientia",
                programs: [
                    "Mechanical Engineering",
                    "Electrical Engineering",
                    "Informatics",
                    "Robotics",
                    "Energy Technology"
                ],
                detailedDescription: "KIT is a leading research university in engineering and natural sciences.",
                popularPrograms: "Engineering, Robotics",
                employmentRate: "93%",
                studentFacultyRatio: "17:1",
                notableAlumni: "Karl Benz"
            },
            {
                name: "Technical University of München",
                rank: "37",
                location: "Munich, Bavaria",
                type: "Public Research (TU)",
                acceptanceRate: "8%",
                internationalStudents: "34%",
                scholarships: "DAAD, TUM",
                founded: "1868",
                totalStudents: "48,000",
                campus: "Urban",
                language: "German, English",
                motto: "The Entrepreneurial University",
                programs: [
                    "Mechanical Engineering",
                    "Computer Science",
                    "Aerospace",
                    "Data Science"
                ],
                detailedDescription: "Germany's top technical university and a global leader in innovation.",
                popularPrograms: "Engineering, Computer Science",
                employmentRate: "94%",
                studentFacultyRatio: "19:1",
                notableAlumni: "Rudolf Diesel"
            },
            {
                name: "Technical University of Stuttgart",
                rank: "301",
                location: "Stuttgart, Baden-Württemberg",
                type: "Public Research (TU)",
                acceptanceRate: "16%",
                internationalStudents: "21%",
                scholarships: "DAAD",
                founded: "1829",
                totalStudents: "24,000",
                campus: "Urban",
                language: "German, English",
                motto: "Automotive and Aerospace",
                programs: [
                    "Automotive Engineering",
                    "Aerospace Engineering",
                    "Civil Engineering",
                    "Architecture"
                ],
                detailedDescription: "Known for automotive and aerospace excellence (home to Porsche, Mercedes).",
                popularPrograms: "Automotive, Aerospace",
                employmentRate: "93%",
                studentFacultyRatio: "20:1",
                notableAlumni: "Gottlieb Daimler"
            },

            // === OTHER ENGINEERING UNIVERSITIES (18) ===
            {
                name: "University of Augsburg",
                rank: "651",
                location: "Augsburg, Bavaria",
                type: "Public Research",
                acceptanceRate: "30%",
                internationalStudents: "12%",
                scholarships: "DAAD",
                founded: "1970",
                totalStudents: "20,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Materials Science", "Computer Science", "Business Informatics"],
                detailedDescription: "Offers engineering-adjacent programs in materials and informatics.",
                popularPrograms: "Materials, Informatics",
                employmentRate: "88%",
                studentFacultyRatio: "25:1",
                notableAlumni: "N/A"
            },
            {
                name: "University of Bayreuth",
                rank: "501",
                location: "Bayreuth, Bavaria",
                type: "Public Research",
                acceptanceRate: "28%",
                internationalStudents: "14%",
                scholarships: "DAAD",
                founded: "1975",
                totalStudents: "13,000",
                campus: "Suburban",
                language: "German, English",
                programs: ["Polymer Engineering", "Materials Science", "Battery Technology"],
                detailedDescription: "Leader in polymer and battery materials.",
                popularPrograms: "Polymer Engineering",
                employmentRate: "89%",
                studentFacultyRatio: "22:1",
                notableAlumni: "N/A"
            },
            {
                name: "University of Ruhr-Bochum",
                rank: "251",
                location: "Bochum, North Rhine-Westphalia",
                type: "Public Research",
                acceptanceRate: "25%",
                internationalStudents: "16%",
                scholarships: "DAAD",
                founded: "1962",
                totalStudents: "43,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Mechanical Engineering", "IT Security", "Electrical Engineering"],
                detailedDescription: "Large university with strong engineering and IT security programs.",
                popularPrograms: "Mechanical, IT Security",
                employmentRate: "87%",
                studentFacultyRatio: "24:1",
                notableAlumni: "N/A"
            },
            {
                name: "University of Bremen",
                rank: "501",
                location: "Bremen",
                type: "Public Research",
                acceptanceRate: "30%",
                internationalStudents: "15%",
                scholarships: "DAAD",
                founded: "1971",
                totalStudents: "19,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Production Engineering", "Space Technology", "Marine Science"],
                detailedDescription: "Focus on production and space technology.",
                popularPrograms: "Production, Space",
                employmentRate: "88%",
                studentFacultyRatio: "23:1",
                notableAlumni: "N/A"
            },
            {
                name: "University of Duisburg-Essen",
                rank: "601",
                location: "Duisburg/Essen",
                type: "Public Research",
                acceptanceRate: "32%",
                internationalStudents: "18%",
                scholarships: "DAAD",
                founded: "2003",
                totalStudents: "42,000",
                campus: "Urban",
                language: "German, English",
                programs: ["NanoEngineering", "Mechanical Engineering", "Medical Engineering"],
                detailedDescription: "Strong in nano and medical engineering.",
                popularPrograms: "NanoEngineering",
                employmentRate: "86%",
                studentFacultyRatio: "26:1",
                notableAlumni: "N/A"
            },
            {
                name: "University of Erlangen-Nürnberg",
                rank: "229",
                location: "Erlangen",
                type: "Public Research",
                acceptanceRate: "20%",
                internationalStudents: "17%",
                scholarships: "DAAD",
                founded: "1743",
                totalStudents: "39,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Medical Engineering", "Materials Science", "Chemical Engineering"],
                detailedDescription: "Leader in medical and materials engineering.",
                popularPrograms: "Medical Engineering",
                employmentRate: "90%",
                studentFacultyRatio: "22:1",
                notableAlumni: "N/A"
            },
            {
                name: "HafenCity University Hamburg (HCU)",
                rank: "N/A",
                location: "Hamburg",
                type: "Public",
                acceptanceRate: "35%",
                internationalStudents: "10%",
                scholarships: "DAAD",
                founded: "2006",
                totalStudents: "2,500",
                campus: "Urban",
                language: "German, English",
                programs: ["Urban Planning", "Civil Engineering", "Architecture"],
                detailedDescription: "Specialized in urban development and planning.",
                popularPrograms: "Urban Planning",
                employmentRate: "85%",
                studentFacultyRatio: "18:1",
                notableAlumni: "N/A"
            },
            {
                name: "Helmut Schmidt University Hamburg",
                rank: "N/A",
                location: "Hamburg",
                type: "Public (Bundeswehr)",
                acceptanceRate: "N/A",
                internationalStudents: "5%",
                scholarships: "Bundeswehr",
                founded: "1972",
                totalStudents: "2,500",
                campus: "Urban",
                language: "German",
                programs: ["Defense Engineering", "Mechanical Engineering", "Economics"],
                detailedDescription: "University for German armed forces officers.",
                popularPrograms: "Defense Engineering",
                employmentRate: "100%",
                studentFacultyRatio: "10:1",
                notableAlumni: "N/A"
            },
            {
                name: "University of Kassel",
                rank: "801",
                location: "Kassel, Hesse",
                type: "Public Research",
                acceptanceRate: "30%",
                internationalStudents: "15%",
                scholarships: "DAAD",
                founded: "1971",
                totalStudents: "25,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Renewable Energy", "Environmental Engineering", "Mechatronics"],
                detailedDescription: "Focus on renewable energy and sustainability.",
                popularPrograms: "Renewable Energy",
                employmentRate: "87%",
                studentFacultyRatio: "24:1",
                notableAlumni: "N/A"
            },
            {
                name: "University of Kiel",
                rank: "501",
                location: "Kiel, Schleswig-Holstein",
                type: "Public Research",
                acceptanceRate: "28%",
                internationalStudents: "14%",
                scholarships: "DAAD",
                founded: "1665",
                totalStudents: "27,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Marine Engineering", "Materials Science", "Food Technology"],
                detailedDescription: "Strong in marine and food engineering.",
                popularPrograms: "Marine Engineering",
                employmentRate: "88%",
                studentFacultyRatio: "23:1",
                notableAlumni: "N/A"
            },
            {
                name: "Otto von Guericke University Magdeburg",
                rank: "801",
                location: "Magdeburg, Saxony-Anhalt",
                type: "Public Research",
                acceptanceRate: "32%",
                internationalStudents: "16%",
                scholarships: "DAAD",
                founded: "1993",
                totalStudents: "14,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Systems Engineering", "Mechanical Engineering", "Medical Technology"],
                detailedDescription: "Focus on systems and medical technology.",
                popularPrograms: "Systems Engineering",
                employmentRate: "86%",
                studentFacultyRatio: "25:1",
                notableAlumni: "N/A"
            },
            {
                name: "University of the Bundeswehr München",
                rank: "N/A",
                location: "Munich",
                type: "Public (Bundeswehr)",
                acceptanceRate: "N/A",
                internationalStudents: "5%",
                scholarships: "Bundeswehr",
                founded: "1973",
                totalStudents: "3,500",
                campus: "Suburban",
                language: "German",
                programs: ["Aerospace Engineering", "Cyber Security", "Mechanical Engineering"],
                detailedDescription: "Bundeswehr university for officer training.",
                popularPrograms: "Aerospace, Cyber",
                employmentRate: "100%",
                studentFacultyRatio: "8:1",
                notableAlumni: "N/A"
            },
            {
                name: "University of Paderborn",
                rank: "801",
                location: "Paderborn, North Rhine-Westphalia",
                type: "Public Research",
                acceptanceRate: "30%",
                internationalStudents: "15%",
                scholarships: "DAAD",
                founded: "1972",
                totalStudents: "20,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Embedded Systems", "Computer Engineering", "Mechanical Engineering"],
                detailedDescription: "Strong in embedded systems and computer engineering.",
                popularPrograms: "Embedded Systems",
                employmentRate: "89%",
                studentFacultyRatio: "22:1",
                notableAlumni: "N/A"
            },
            {
                name: "University of Rostock",
                rank: "701",
                location: "Rostock, Mecklenburg-Vorpommern",
                type: "Public Research",
                acceptanceRate: "35%",
                internationalStudents: "12%",
                scholarships: "DAAD",
                founded: "1419",
                totalStudents: "14,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Shipbuilding", "Mechanical Engineering", "Electrical Engineering"],
                detailedDescription: "Oldest university in Northern Europe, strong in shipbuilding.",
                popularPrograms: "Shipbuilding",
                employmentRate: "87%",
                studentFacultyRatio: "24:1",
                notableAlumni: "Tycho Brahe"
            },
            {
                name: "University of Saarland",
                rank: "601",
                location: "Saarbrücken, Saarland",
                type: "Public Research",
                acceptanceRate: "25%",
                internationalStudents: "18%",
                scholarships: "DAAD",
                founded: "1948",
                totalStudents: "17,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Computer Science", "Mechatronics", "Materials Science"],
                detailedDescription: "Strong in computer science and mechatronics.",
                popularPrograms: "Computer Science",
                employmentRate: "90%",
                studentFacultyRatio: "20:1",
                notableAlumni: "N/A"
            },
            {
                name: "University of Siegen",
                rank: "1001",
                location: "Siegen, North Rhine-Westphalia",
                type: "Public Research",
                acceptanceRate: "32%",
                internationalStudents: "14%",
                scholarships: "DAAD",
                founded: "1972",
                totalStudents: "19,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Sensor Systems", "Mechanical Engineering", "Mechatronics"],
                detailedDescription: "Specializes in sensor technology.",
                popularPrograms: "Sensor Systems",
                employmentRate: "86%",
                studentFacultyRatio: "25:1",
                notableAlumni: "N/A"
            },
            {
                name: "University of Ulm",
                rank: "351",
                location: "Ulm, Baden-Württemberg",
                type: "Public Research",
                acceptanceRate: "20%",
                internationalStudents: "16%",
                scholarships: "DAAD",
                founded: "1967",
                totalStudents: "10,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Electric Mobility", "Medical Engineering", "Computer Science"],
                detailedDescription: "Focus on electric mobility and medical engineering.",
                popularPrograms: "Electric Mobility",
                employmentRate: "91%",
                studentFacultyRatio: "18:1",
                notableAlumni: "N/A"
            },
            {
                name: "University of Wuppertal",
                rank: "901",
                location: "Wuppertal, North Rhine-Westphalia",
                type: "Public Research",
                acceptanceRate: "30%",
                internationalStudents: "15%",
                scholarships: "DAAD",
                founded: "1972",
                totalStudents: "22,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Safety Engineering", "Industrial Design", "Civil Engineering"],
                detailedDescription: "Strong in safety and industrial design.",
                popularPrograms: "Safety Engineering",
                employmentRate: "87%",
                studentFacultyRatio: "24:1",
                notableAlumni: "N/A"
            },

            // === UNIVERSITIES OF APPLIED SCIENCES (UAS) ===
            {
                name: "FH Aachen University of Applied Sciences",
                rank: "N/A",
                location: "Aachen",
                type: "UAS",
                acceptanceRate: "40%",
                internationalStudents: "20%",
                scholarships: "DAAD",
                founded: "1971",
                totalStudents: "15,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Aerospace", "Mechanical", "Electrical"],
                detailedDescription: "One of the largest UAS in Germany with strong engineering programs.",
                popularPrograms: "Aerospace, Engineering",
                employmentRate: "92%",
                studentFacultyRatio: "30:1",
                notableAlumni: "N/A"
            },
            {
                name: "Hamburg University of Applied Sciences",
                rank: "N/A",
                location: "Hamburg",
                type: "UAS",
                acceptanceRate: "45%",
                internationalStudents: "18%",
                scholarships: "DAAD",
                founded: "1970",
                totalStudents: "17,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Life Sciences", "Media", "Engineering"],
                detailedDescription: "Focus on applied sciences and media.",
                popularPrograms: "Engineering, Media",
                employmentRate: "90%",
                studentFacultyRatio: "32:1",
                notableAlumni: "N/A"
            },
            {
                name: "Berlin International University of Applied Sciences",
                rank: "N/A",
                location: "Berlin",
                type: "UAS (Private)",
                acceptanceRate: "60%",
                internationalStudents: "80%",
                scholarships: "Merit-based",
                founded: "2014",
                totalStudents: "1,000",
                campus: "Urban",
                language: "English",
                programs: ["Design", "Business", "Architecture"],
                detailedDescription: "Fully English-taught private UAS.",
                popularPrograms: "Design, Business",
                employmentRate: "85%",
                studentFacultyRatio: "15:1",
                notableAlumni: "N/A"
            },
            {
                name: "Beuth University of Applied Sciences Berlin",
                rank: "N/A",
                location: "Berlin",
                type: "UAS",
                acceptanceRate: "40%",
                internationalStudents: "20%",
                scholarships: "DAAD",
                founded: "1823",
                totalStudents: "13,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Engineering", "Informatics", "Media"],
                detailedDescription: "Large UAS with strong engineering focus.",
                popularPrograms: "Engineering",
                employmentRate: "91%",
                studentFacultyRatio: "28:1",
                notableAlumni: "N/A"
            },
            {
                name: "Dortmund University of Applied Sciences and Arts",
                rank: "N/A",
                location: "Dortmund",
                type: "UAS",
                acceptanceRate: "45%",
                internationalStudents: "16%",
                scholarships: "DAAD",
                founded: "1971",
                totalStudents: "14,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Applied Informatics", "Engineering", "Design"],
                detailedDescription: "Focus on applied informatics and design.",
                popularPrograms: "Informatics",
                employmentRate: "89%",
                studentFacultyRatio: "30:1",
                notableAlumni: "N/A"
            },
            {
                name: "Darmstadt University of Applied Sciences",
                rank: "N/A",
                location: "Darmstadt",
                type: "UAS",
                acceptanceRate: "40%",
                internationalStudents: "18%",
                scholarships: "DAAD",
                founded: "1971",
                totalStudents: "16,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Media", "Engineering", "Social Work"],
                detailedDescription: "Strong in media and engineering.",
                popularPrograms: "Engineering",
                employmentRate: "90%",
                studentFacultyRatio: "29:1",
                notableAlumni: "N/A"
            },
            {
                name: "Munich University of Applied Sciences",
                rank: "N/A",
                location: "Munich",
                type: "UAS",
                acceptanceRate: "38%",
                internationalStudents: "20%",
                scholarships: "DAAD",
                founded: "1971",
                totalStudents: "18,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Automotive", "Aeronautics", "Engineering"],
                detailedDescription: "Largest UAS in Bavaria.",
                popularPrograms: "Automotive",
                employmentRate: "93%",
                studentFacultyRatio: "28:1",
                notableAlumni: "N/A"
            },
            {
                name: "RheinMain University of Applied Sciences",
                rank: "N/A",
                location: "Wiesbaden",
                type: "UAS",
                acceptanceRate: "42%",
                internationalStudents: "17%",
                scholarships: "DAAD",
                founded: "1971",
                totalStudents: "13,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Engineering", "Media", "Business"],
                detailedDescription: "Focus on applied engineering and media.",
                popularPrograms: "Engineering",
                employmentRate: "89%",
                studentFacultyRatio: "30:1",
                notableAlumni: "N/A"
            },
            {
                name: "Rhine-Waal University of Applied Sciences",
                rank: "N/A",
                location: "Kleve",
                type: "UAS",
                acceptanceRate: "50%",
                internationalStudents: "60%",
                scholarships: "DAAD",
                founded: "2009",
                totalStudents: "7,500",
                campus: "Rural",
                language: "English, German",
                programs: ["International Engineering", "Sustainable Development"],
                detailedDescription: "Fully English-taught programs.",
                popularPrograms: "International Engineering",
                employmentRate: "88%",
                studentFacultyRatio: "25:1",
                notableAlumni: "N/A"
            },

            // === TECHNISCHE HOCHSCHULE (TH) ===
            {
                name: "TH Bingen",
                rank: "N/A",
                location: "Bingen",
                type: "UAS (TH)",
                acceptanceRate: "45%",
                internationalStudents: "15%",
                scholarships: "DAAD",
                founded: "1897",
                totalStudents: "2,800",
                campus: "Small Town",
                language: "German, English",
                programs: ["Engineering", "Agriculture", "Environmental Tech"],
                detailedDescription: "Focus on applied engineering and agriculture.",
                popularPrograms: "Engineering",
                employmentRate: "90%",
                studentFacultyRatio: "20:1",
                notableAlumni: "N/A"
            },
            {
                name: "TH Deggendorf",
                rank: "N/A",
                location: "Deggendorf",
                type: "UAS (TH)",
                acceptanceRate: "40%",
                internationalStudents: "25%",
                scholarships: "DAAD",
                founded: "1994",
                totalStudents: "7,000",
                campus: "Small Town",
                language: "German, English",
                programs: ["Mechatronics", "AI", "Health Informatics"],
                detailedDescription: "Strong in AI and mechatronics.",
                popularPrograms: "Mechatronics",
                employmentRate: "92%",
                studentFacultyRatio: "22:1",
                notableAlumni: "N/A"
            },
            {
                name: "TH Köln",
                rank: "N/A",
                location: "Cologne",
                type: "UAS (TH)",
                acceptanceRate: "38%",
                internationalStudents: "20%",
                scholarships: "DAAD",
                founded: "1971",
                totalStudents: "27,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Engineering", "Culture", "Architecture"],
                detailedDescription: "Largest UAS in Germany.",
                popularPrograms: "Engineering",
                employmentRate: "91%",
                studentFacultyRatio: "30:1",
                notableAlumni: "N/A"
            },
            {
                name: "TH Ingolstadt",
                rank: "N/A",
                location: "Ingolstadt",
                type: "UAS (TH)",
                acceptanceRate: "35%",
                internationalStudents: "22%",
                scholarships: "DAAD",
                founded: "1994",
                totalStudents: "6,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Automotive", "Mobility", "AI"],
                detailedDescription: "Close ties with Audi and automotive industry.",
                popularPrograms: "Automotive",
                employmentRate: "94%",
                studentFacultyRatio: "20:1",
                notableAlumni: "N/A"
            },
            {
                name: "TH Lübeck",
                rank: "N/A",
                location: "Lübeck",
                type: "UAS (TH)",
                acceptanceRate: "42%",
                internationalStudents: "18%",
                scholarships: "DAAD",
                founded: "1808",
                totalStudents: "5,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Applied Natural Sciences", "Engineering"],
                detailedDescription: "Focus on applied sciences.",
                popularPrograms: "Engineering",
                employmentRate: "89%",
                studentFacultyRatio: "25:1",
                notableAlumni: "N/A"
            },
            {
                name: "TH Mittelhessen",
                rank: "N/A",
                location: "Giessen",
                type: "UAS (TH)",
                acceptanceRate: "40%",
                internationalStudents: "16%",
                scholarships: "DAAD",
                founded: "1971",
                totalStudents: "18,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Engineering", "Health", "Business"],
                detailedDescription: "Large UAS with multiple campuses.",
                popularPrograms: "Engineering",
                employmentRate: "90%",
                studentFacultyRatio: "28:1",
                notableAlumni: "N/A"
            },
            {
                name: "TH Nuremberg",
                rank: "N/A",
                location: "Nuremberg",
                type: "UAS (TH)",
                acceptanceRate: "38%",
                internationalStudents: "20%",
                scholarships: "DAAD",
                founded: "1823",
                totalStudents: "13,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Engineering", "Business", "Social Sciences"],
                detailedDescription: "One of the oldest UAS in Germany.",
                popularPrograms: "Engineering",
                employmentRate: "91%",
                studentFacultyRatio: "27:1",
                notableAlumni: "N/A"
            },
            {
                name: "OTH Regensburg",
                rank: "N/A",
                location: "Regensburg",
                type: "UAS (TH)",
                acceptanceRate: "40%",
                internationalStudents: "18%",
                scholarships: "DAAD",
                founded: "1971",
                totalStudents: "11,000",
                campus: "Urban",
                language: "German, English",
                programs: ["Sensor Technology", "Engineering", "Business"],
                detailedDescription: "Focus on sensor technology.",
                popularPrograms: "Sensor Technology",
                employmentRate: "90%",
                studentFacultyRatio: "26:1",
                notableAlumni: "N/A"
            },
            {
                name: "TH Rosenheim",
                rank: "N/A",
                location: "Rosenheim",
                type: "UAS (TH)",
                acceptanceRate: "42%",
                internationalStudents: "17%",
                scholarships: "DAAD",
                founded: "1971",
                totalStudents: "6,000",
                campus: "Small Town",
                language: "German, English",
                programs: ["Wood Technology", "Construction", "Engineering"],
                detailedDescription: "Specializes in wood and construction engineering.",
                popularPrograms: "Wood Technology",
                employmentRate: "89%",
                studentFacultyRatio: "24:1",
                notableAlumni: "N/A"
            },

            // === DUAL UNIVERSITIES ===
            {
                name: "Baden-Württemberg Cooperative State University",
                rank: "N/A",
                location: "Multiple (9 campuses)",
                type: "Dual University",
                acceptanceRate: "N/A (Company-based)",
                internationalStudents: "10%",
                scholarships: "Company Salary",
                founded: "1974",
                totalStudents: "34,000",
                campus: "Multiple",
                language: "German, English",
                programs: [
                    "Engineering",
                    "Business",
                    "IT",
                    "Health"
                ],
                detailedDescription: "Largest dual university in Germany. Students work and study simultaneously, paid by partner companies.",
                popularPrograms: "Dual Engineering",
                employmentRate: "99%",
                studentFacultyRatio: "N/A",
                notableAlumni: "N/A"
            },
            {
                name: "Duale Hochschule Gera-Eisenach",
                rank: "N/A",
                location: "Gera/Eisenach",
                type: "Dual University",
                acceptanceRate: "N/A",
                internationalStudents: "8%",
                scholarships: "Company Salary",
                founded: "2016",
                totalStudents: "1,500",
                campus: "Urban",
                language: "German",
                programs: ["Engineering", "Business"],
                detailedDescription: "Dual study with paid industry training.",
                popularPrograms: "Dual Engineering",
                employmentRate: "98%",
                studentFacultyRatio: "N/A",
                notableAlumni: "N/A"
            },
            {
                name: "Sachsen University of Cooperative Education",
                rank: "N/A",
                location: "Multiple (Saxony)",
                type: "Dual University",
                acceptanceRate: "N/A",
                internationalStudents: "10%",
                scholarships: "Company Salary",
                founded: "1991",
                totalStudents: "5,000",
                campus: "Multiple",
                language: "German",
                programs: ["Technical", "Commercial"],
                detailedDescription: "Dual study model across Saxony.",
                popularPrograms: "Dual Technical",
                employmentRate: "99%",
                studentFacultyRatio: "N/A",
                notableAlumni: "N/A"
            }
        ]
    },
    {
        name: "Japan",
        flag: "https://flagcdn.com/jp.svg",
        capital: "Tokyo",
        language: "Japanese",
        currency: "JPY (¥)",
        details: "Japan combines cutting-edge technology with rich cultural heritage, offering unique educational experiences in advanced research and innovation.",
        rank: "Top 30 Globally",
        programs: "1500+ Programs",
        topRanked: "10",
        students: "300K+",
        programsCount: "1800+",
        universities: [
            {
                name: "University of Tokyo",
                rank: "28",
                location: "Tokyo",
                type: "Public Research",
                acceptanceRate: "21%",
                internationalStudents: "12%",
                scholarships: "MEXT Scholarships",
                founded: "1877",
                totalStudents: "28,000",
                campus: "Urban",
                language: "Japanese, English",
                motto: "None officially",
                programs: [
                    "Engineering",
                    "Medicine",
                    "Law",
                    "Science",
                    "Agriculture",
                    "Economics",
                    "Arts and Sciences"
                ],
                detailedDescription: "The University of Tokyo is a public research university located in Tokyo, Japan. It is the first of Japan's National Seven Universities and is considered the most selective and prestigious university in Japan.",
                popularPrograms: "Engineering, Medicine, Law",
                employmentRate: "95%",
                studentFacultyRatio: "9:1",
                notableAlumni: "Yukio Hatoyama, Kenzaburō Ōe, Leo Esaki"
            },
            {
                name: "Kyoto University",
                rank: "46",
                location: "Kyoto",
                type: "Public Research",
                acceptanceRate: "30%",
                internationalStudents: "9%",
                scholarships: "MEXT, Kyoto University",
                founded: "1897",
                totalStudents: "22,000",
                campus: "Urban",
                language: "Japanese, English",
                motto: "Freedom of academic culture",
                programs: [
                    "Engineering",
                    "Medicine",
                    "Science",
                    "Law",
                    "Economics",
                    "Agriculture",
                    "Humanities"
                ],
                detailedDescription: "Kyoto University is a national university in Kyoto, Japan. It is the second oldest Japanese university, one of the top universities in Asia and the National Seven Universities.",
                popularPrograms: "Engineering, Science, Medicine",
                employmentRate: "92%",
                studentFacultyRatio: "8:1",
                notableAlumni: "Hideki Yukawa, Shinichiro Tomonaga, Tasuku Honjo"
            },
            {
                name: "Tokyo Institute of Technology",
                rank: "55",
                location: "Tokyo",
                type: "Public Research",
                acceptanceRate: "15%",
                internationalStudents: "16%",
                scholarships: "MEXT, Tokyo Tech",
                founded: "1881",
                totalStudents: "10,000",
                campus: "Urban",
                language: "Japanese, English",
                motto: "Jikyu gakujutsu wo tsurugi to nashi (To make the latest science and technology our sword)",
                programs: [
                    "Mechanical Engineering",
                    "Electrical Engineering",
                    "Computer Science",
                    "Chemistry",
                    "Physics",
                    "Mathematics",
                    "Bioscience"
                ],
                detailedDescription: "Tokyo Institute of Technology is a national research university located in Tokyo, Japan. Tokyo Tech is the largest institution for higher education in Japan dedicated to science and technology.",
                popularPrograms: "Engineering, Computer Science, Natural Sciences",
                employmentRate: "96%",
                studentFacultyRatio: "7:1",
                notableAlumni: "Hideki Shirakawa, Noritaka Tatehana, Takashi Kubota"
            }
        ]
    }
];

export default countries;